import type { CardDef } from '../../engine/types'

// 冒险第二章「逐鹿千年」几位雄主主公技召唤的衍生物。
// 比第一章的 1/1 力士/门客更硬一档——历代精锐,也把关底主公技的分量拉起来。
// token:true,只能被召唤,不进卡包、不可构筑。中立,不污染任何势力池。

export const CAMPAIGN_TOKENS: CardDef[] = [
  {
    id: 'token-tie-qi',
    collectorNo: 9971,
    name: { zh: '鐵騎', en: 'Ironclad Cavalry' },
    troop: 'cavalry',
    type: 'general',
    doctrine: 'neutral',
    dynasty: 'qun',
    rarity: 'common',
    archetype: 'warrior',
    cost: 2,
    attack: 2,
    health: 2,
    keywords: [],
    token: true,
    text: { zh: '', en: '' },
  },
  {
    id: 'token-jin-jun',
    collectorNo: 9972,
    name: { zh: '禁軍', en: 'Imperial Guard' },
    troop: 'infantry',
    type: 'general',
    doctrine: 'neutral',
    dynasty: 'qun',
    rarity: 'common',
    archetype: 'warrior',
    cost: 3,
    attack: 3,
    health: 3,
    keywords: [],
    token: true,
    text: { zh: '', en: '' },
  },

  // ---- 关底试炼(BossDef.trial)的目标单位 ----
  //
  // 斩将类给**守护**:逼你先啃穿它才够得着,不然贪心 AI 那套「谁血少打谁」
  // 会让目标一直躲在后排(名局那边同一个教训,见 historyBattles 顶部注释)。
  // 护送类给 **0 攻高血**:AI 天然懒得打 0 攻单位,但一旦被 AOE 扫到就危险 ——
  // 难度刚好落在「不用一直看着,但也不能忘了它」。
  {
    id: 'token-hua-xiong',
    collectorNo: 9973,
    name: { zh: '華雄', en: 'Hua Xiong' },
    troop: 'infantry',
    type: 'general',
    doctrine: 'neutral',
    dynasty: 'qun',
    rarity: 'common',
    archetype: 'warrior',
    cost: 5,
    attack: 4,
    health: 7,
    keywords: ['guard'],
    token: true,
    text: { zh: '', en: '' },
  },
  {
    id: 'token-chunyu-qiong',
    collectorNo: 9974,
    name: { zh: '淳于瓊', en: 'Chunyu Qiong' },
    troop: 'infantry',
    type: 'general',
    doctrine: 'neutral',
    dynasty: 'qun',
    rarity: 'common',
    archetype: 'warrior',
    cost: 5,
    attack: 2,
    health: 9,
    keywords: ['guard'],
    token: true,
    text: { zh: '', en: '' },
  },
  {
    id: 'token-di-zhu-jiang',
    collectorNo: 9975,
    name: { zh: '敵軍主將', en: 'Enemy Commander' },
    troop: 'cavalry',
    type: 'general',
    doctrine: 'neutral',
    dynasty: 'qun',
    rarity: 'common',
    archetype: 'warrior',
    cost: 7,
    attack: 5,
    health: 10,
    keywords: ['guard'],
    token: true,
    text: { zh: '', en: '' },
  },
  {
    id: 'token-liang-che',
    collectorNo: 9976,
    name: { zh: '糧車', en: 'Grain Cart' },
    troop: 'siege',
    type: 'general',
    doctrine: 'neutral',
    dynasty: 'qun',
    rarity: 'common',
    archetype: 'warrior',
    cost: 3,
    attack: 0,
    health: 8,
    keywords: [],
    token: true,
    text: { zh: '', en: '' },
  },
]
