import type { CardDef } from '../../engine/types'

// 第二卡包「神兵天降」:装备牌(id 前缀 eq-,collectorNo 9101 起)
// + 新锦囊(沿用 strat- 前缀,collectorNo 9016 起)。
// 新机制:吸血 lifesteal / 剧毒 poison / 护甲 gainArmor / 弹回 returnToHand / 弃牌 discardRandom。
// 装备语义:打给一名友方在场武将,attack/health 为加成值,keywords 为授予的关键词。
// 计价基线:加成 +1/+1 ≈ 1费;冲锋/剧毒/吸血 +1费,守护/突袭/连击 +0.5费。

export const EQUIPMENT: CardDef[] = [
  {
    id: 'eq-qinglong-dao',
    collectorNo: 9101,
    name: { zh: '青龍偃月刀', en: 'Green Dragon Crescent Blade' },
    type: 'equipment',
    doctrine: 'royal',
    dynasty: 'shu',
    rarity: 'epic',
    archetype: 'warrior',
    cost: 4,
    attack: 3,
    health: 1,
    keywords: ['windfury'],
    text: { zh: '友方武將+3/+1並獲得連擊。刀重八十二斤,冷豔鋸沉。', en: 'Give a friendly general +3/+1 and Windfury.' },
  },
  {
    id: 'eq-fangtian-ji',
    collectorNo: 9102,
    name: { zh: '方天畫戟', en: 'Sky-Piercer Halberd' },
    type: 'equipment',
    doctrine: 'hegemonic',
    dynasty: 'qun',
    rarity: 'epic',
    archetype: 'warrior',
    cost: 6,
    attack: 4,
    health: 2,
    keywords: ['charge'],
    text: { zh: '友方武將+4/+2並獲得衝鋒。轅門一戟,遼東無雙。', en: 'Give a friendly general +4/+2 and Charge.' },
  },
  {
    id: 'eq-zhangba-mao',
    collectorNo: 9103,
    name: { zh: '丈八蛇矛', en: 'Serpent Spear' },
    type: 'equipment',
    doctrine: 'royal',
    dynasty: 'shu',
    rarity: 'rare',
    archetype: 'warrior',
    cost: 3,
    attack: 3,
    health: 2,
    keywords: [],
    text: { zh: '友方武將+3/+2。長阪橋頭一聲吼,水倒流。', en: 'Give a friendly general +3/+2.' },
  },
  {
    id: 'eq-yitian-jian',
    collectorNo: 9104,
    name: { zh: '倚天劍', en: 'Sword of Heaven' },
    type: 'equipment',
    doctrine: 'hegemonic',
    dynasty: 'wei',
    rarity: 'rare',
    archetype: 'warrior',
    cost: 4,
    attack: 3,
    health: 3,
    keywords: [],
    text: { zh: '友方武將+3/+3。倚天不出,誰與爭鋒。', en: 'Give a friendly general +3/+3.' },
  },
  {
    id: 'eq-qinggang-jian',
    collectorNo: 9105,
    name: { zh: '青釭劍', en: 'Qinggang Sword' },
    type: 'equipment',
    doctrine: 'neutral',
    dynasty: 'wei',
    rarity: 'epic',
    archetype: 'warrior',
    cost: 3,
    attack: 1,
    health: 1,
    keywords: ['poison'],
    text: { zh: '友方武將+1/+1並獲得劇毒。削鐵如泥,觸之即殞。', en: 'Give a friendly general +1/+1 and Poison.' },
  },
  {
    id: 'eq-guding-dao',
    collectorNo: 9106,
    name: { zh: '古錠刀', en: 'Ancient Ingot Blade' },
    type: 'equipment',
    doctrine: 'separatist',
    dynasty: 'qun',
    rarity: 'rare',
    archetype: 'warrior',
    cost: 3,
    attack: 2,
    health: 1,
    keywords: ['lifesteal'],
    text: { zh: '友方武將+2/+1並獲得吸血。江東猛虎,飲血而歸。', en: 'Give a friendly general +2/+1 and Lifesteal.' },
  },
  {
    id: 'eq-qixing-dao',
    collectorNo: 9107,
    name: { zh: '七星寶刀', en: 'Seven Star Blade' },
    type: 'equipment',
    doctrine: 'neutral',
    dynasty: 'wei',
    rarity: 'epic',
    archetype: 'strategist',
    cost: 2,
    attack: 0,
    health: 1,
    keywords: ['poison'],
    text: { zh: '友方武將+0/+1並獲得劇毒。獻刀者,藏鋒者也。', en: 'Give a friendly general +0/+1 and Poison.' },
  },
  {
    id: 'eq-bawang-qiang',
    collectorNo: 9108,
    name: { zh: '霸王槍', en: 'Overlord Spear' },
    type: 'equipment',
    doctrine: 'hegemonic',
    dynasty: 'chu-han',
    rarity: 'epic',
    archetype: 'warrior',
    cost: 6,
    attack: 5,
    health: 3,
    keywords: [],
    text: { zh: '友方武將+5/+3。力拔山兮氣蓋世。', en: 'Give a friendly general +5/+3.' },
  },
  {
    id: 'eq-longdan-qiang',
    collectorNo: 9109,
    name: { zh: '龍膽亮銀槍', en: 'Dragon Gall Spear' },
    type: 'equipment',
    doctrine: 'royal',
    dynasty: 'shu',
    rarity: 'rare',
    archetype: 'warrior',
    cost: 4,
    attack: 3,
    health: 2,
    keywords: ['rush'],
    text: { zh: '友方武將+3/+2並獲得突襲。七進七出,渾身是膽。', en: 'Give a friendly general +3/+2 and Rush.' },
  },
  {
    id: 'eq-qilin-gong',
    collectorNo: 9110,
    name: { zh: '麒麟弓', en: 'Qilin Bow' },
    type: 'equipment',
    doctrine: 'neutral',
    dynasty: 'shu',
    rarity: 'rare',
    archetype: 'warrior',
    cost: 2,
    attack: 2,
    health: 0,
    keywords: ['windfury'],
    text: { zh: '友方武將+2/+0並獲得連擊。百步穿楊,箭無虛發。', en: 'Give a friendly general +2/+0 and Windfury.' },
  },
  {
    id: 'eq-zhanlu-jian',
    collectorNo: 9111,
    name: { zh: '湛盧劍', en: 'Zhanlu Sword' },
    type: 'equipment',
    doctrine: 'ritual',
    dynasty: 'spring-autumn',
    rarity: 'rare',
    archetype: 'warrior',
    cost: 3,
    attack: 2,
    health: 3,
    keywords: [],
    text: { zh: '友方武將+2/+3。仁道之劍,無鋒而利。', en: 'Give a friendly general +2/+3.' },
  },
  {
    id: 'eq-ganjiang-moye',
    collectorNo: 9112,
    name: { zh: '干將莫邪', en: 'Ganjiang & Moye' },
    type: 'equipment',
    doctrine: 'fame',
    dynasty: 'spring-autumn',
    rarity: 'epic',
    archetype: 'warrior',
    cost: 4,
    attack: 2,
    health: 2,
    keywords: ['windfury'],
    text: { zh: '友方武將+2/+2並獲得連擊。雌雄雙劍,鑄以魂魄。', en: 'Give a friendly general +2/+2 and Windfury.' },
  },
  {
    id: 'eq-mingguang-kai',
    collectorNo: 9113,
    name: { zh: '明光鎧', en: 'Radiant Armor' },
    type: 'equipment',
    doctrine: 'neutral',
    dynasty: 'tang',
    rarity: 'common',
    archetype: 'warrior',
    cost: 3,
    attack: 0,
    health: 4,
    keywords: ['guard'],
    text: { zh: '友方武將+0/+4並獲得守護。甲光向日金鱗開。', en: 'Give a friendly general +0/+4 and Guard.' },
  },
  {
    id: 'eq-teng-jia',
    collectorNo: 9114,
    name: { zh: '藤甲', en: 'Rattan Armor' },
    type: 'equipment',
    doctrine: 'neutral',
    dynasty: 'qun',
    rarity: 'common',
    archetype: 'warrior',
    cost: 2,
    attack: 0,
    health: 3,
    keywords: ['guard'],
    text: { zh: '友方武將+0/+3並獲得守護。渡江不沉,刀箭不入。', en: 'Give a friendly general +0/+3 and Guard.' },
  },
  {
    id: 'eq-chitu-ma',
    collectorNo: 9115,
    name: { zh: '赤兔馬', en: 'Red Hare' },
    type: 'equipment',
    doctrine: 'neutral',
    dynasty: 'qun',
    rarity: 'epic',
    archetype: 'warrior',
    cost: 3,
    attack: 2,
    health: 0,
    keywords: ['charge'],
    text: { zh: '友方武將+2/+0並獲得衝鋒。人中呂布,馬中赤兔。', en: 'Give a friendly general +2/+0 and Charge.' },
  },
  {
    id: 'eq-dilu-ma',
    collectorNo: 9116,
    name: { zh: '的盧馬', en: 'Dilu Steed' },
    type: 'equipment',
    doctrine: 'neutral',
    dynasty: 'shu',
    rarity: 'common',
    archetype: 'warrior',
    cost: 2,
    attack: 1,
    health: 2,
    keywords: ['rush'],
    text: { zh: '友方武將+1/+2並獲得突襲。一躍三丈,馬躍檀溪。', en: 'Give a friendly general +1/+2 and Rush.' },
  },
]

export const PACK2_STRATAGEMS: CardDef[] = [
  {
    id: 'strat-diaohu-lishan',
    collectorNo: 9016,
    name: { zh: '調虎離山', en: 'Lure the Tiger' },
    type: 'stratagem',
    doctrine: 'fame',
    dynasty: 'qun',
    rarity: 'rare',
    archetype: 'strategist',
    cost: 3,
    keywords: [],
    spell: { ops: [{ op: 'returnToHand', target: 'chosenEnemyGeneral' }] },
    text: { zh: '將一名敵方武將彈回其手牌。虎離深山,爪牙何施。', en: 'Return an enemy general to its owner’s hand.' },
  },
  {
    id: 'strat-jinchan-tuoke',
    collectorNo: 9017,
    name: { zh: '金蟬脫殼', en: 'Golden Cicada Sheds' },
    type: 'stratagem',
    doctrine: 'reclusion',
    dynasty: 'qun',
    rarity: 'rare',
    archetype: 'strategist',
    cost: 1,
    keywords: [],
    spell: { ops: [{ op: 'returnToHand', target: 'chosenAny' }] },
    text: { zh: '將任一武將彈回其手牌。蟬蛻於濁穢,以浮游塵埃之外。', en: 'Return any general to its owner’s hand.' },
  },
  {
    id: 'strat-fudi-chouxin',
    collectorNo: 9018,
    name: { zh: '釜底抽薪', en: 'Steal the Firewood' },
    type: 'stratagem',
    doctrine: 'fame',
    dynasty: 'warring-states',
    rarity: 'rare',
    archetype: 'strategist',
    cost: 3,
    keywords: [],
    spell: { ops: [{ op: 'discardRandom', count: 2 }] },
    text: { zh: '對手隨機棄兩張牌。不敵其力,而消其勢。', en: 'Your opponent discards 2 random cards.' },
  },
  {
    id: 'strat-duanqi-liangdao',
    collectorNo: 9019,
    name: { zh: '斷其糧道', en: 'Sever the Supply Line' },
    type: 'stratagem',
    doctrine: 'hegemonic',
    dynasty: 'wei',
    rarity: 'common',
    archetype: 'strategist',
    cost: 3,
    keywords: [],
    spell: {
      ops: [
        { op: 'discardRandom', count: 1 },
        { op: 'damage', amount: 2, target: 'enemyHero' },
      ],
    },
    text: { zh: '對手隨機棄一張牌,並對敵方主公造成2點傷害。烏巢一炬,四世三公成灰。', en: 'Opponent discards a card; deal 2 damage to the enemy hero.' },
  },
  {
    id: 'strat-jianbi-qingye',
    collectorNo: 9020,
    name: { zh: '堅壁清野', en: 'Fortify the Walls' },
    type: 'stratagem',
    doctrine: 'neutral',
    dynasty: 'warring-states',
    rarity: 'common',
    archetype: 'strategist',
    cost: 3,
    keywords: [],
    spell: { ops: [{ op: 'gainArmor', amount: 5 }] },
    text: { zh: '我方主公獲得5點護甲。深壁固壘,勿與戰。', en: 'Gain 5 Armor.' },
  },
  {
    id: 'strat-libing-moma',
    collectorNo: 9021,
    name: { zh: '厲兵秣馬', en: 'Sharpen the Blades' },
    type: 'stratagem',
    doctrine: 'neutral',
    dynasty: 'spring-autumn',
    rarity: 'rare',
    archetype: 'strategist',
    cost: 3,
    keywords: [],
    spell: {
      ops: [
        { op: 'gainArmor', amount: 3 },
        { op: 'draw', count: 1 },
      ],
    },
    text: { zh: '我方主公獲得3點護甲,抽一張牌。枕戈待旦,兵不解甲。', en: 'Gain 3 Armor and draw a card.' },
  },
  {
    id: 'strat-cuidu-zhiren',
    collectorNo: 9022,
    name: { zh: '淬毒之刃', en: 'Envenomed Edge' },
    type: 'stratagem',
    doctrine: 'separatist',
    dynasty: 'warring-states',
    rarity: 'epic',
    archetype: 'strategist',
    cost: 2,
    keywords: [],
    spell: { ops: [{ op: 'grantKeyword', keyword: 'poison', target: 'chosenAny' }] },
    text: { zh: '使任一武將獲得劇毒。見血封喉,不論強弱。', en: 'Give any general Poison.' },
  },
  {
    id: 'strat-yuxue-fenzhan',
    collectorNo: 9023,
    name: { zh: '浴血奮戰', en: 'Bathed in Blood' },
    type: 'stratagem',
    doctrine: 'hegemonic',
    dynasty: 'chu-han',
    rarity: 'rare',
    archetype: 'warrior',
    cost: 3,
    keywords: [],
    spell: {
      ops: [
        { op: 'grantKeyword', keyword: 'lifesteal', target: 'chosenAny' },
        { op: 'buffStats', attack: 1, health: 1, target: 'chosenAny' },
      ],
    },
    text: { zh: '使任一武將獲得吸血並+1/+1。破釜沉舟,以戰養戰。', en: 'Give any general Lifesteal and +1/+1.' },
  },
]

export const PACK2_CARDS: CardDef[] = [...EQUIPMENT, ...PACK2_STRATAGEMS]
