import type { CardDef } from '../../engine/types'

// 签名卡手工调校层:覆盖生成公式的默认值。
// 键 = 武将 id(与姊妹仓库一致,必须存在于 cards.gen.ts)。这里只放与生成值不同的字段。
// 设计基线:白板曲线 总身材 ≈ cost*2+1,关键词与效果按约 1~2 点身材/费计价。
// 关键词译名:衝鋒 charge / 突襲 rush / 守護 guard / 連擊 windfury / 單挑 duel。
export const SIGNATURE_OVERRIDES: Record<string, Partial<CardDef>> = {
  // ================= 王道 royal =================
  'liu-bei': {
    dynasty: 'shu',
    doctrine: 'royal',
    cost: 6,
    attack: 5,
    health: 6,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方蜀勢力武將+1/+1。仁德載世,三顧乃見。', en: 'Battlecry: Give your Shu generals +1/+1.' },
  },
  'guan-yu': {
    dynasty: 'shu',
    doctrine: 'royal',
    rarity: 'legendary',
    cost: 7,
    attack: 7,
    health: 7,
    keywords: ['duel'],
    text: { zh: '單挑。溫酒斬將,千里走單騎。', en: 'Duel. The Saint of War rides a thousand li alone.' },
  },
  'zhang-fei': {
    dynasty: 'shu',
    doctrine: 'royal',
    rarity: 'epic',
    cost: 6,
    attack: 6,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。當陽橋頭一聲吼,喝斷橋樑水倒流。', en: 'Guard. One roar at Changban Bridge turned the river back.' },
  },
  'zhao-yun': {
    dynasty: 'shu',
    doctrine: 'royal',
    cost: 7,
    attack: 6,
    health: 6,
    keywords: ['charge'],
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '衝鋒。戰吼:抽一張牌。長坂單騎救主,懷抱幼主而還。', en: 'Charge. Battlecry: Draw a card. He rode alone through Changban and returned with the young lord.' },
  },
  'zhuge-liang': {
    dynasty: 'shu',
    doctrine: 'royal',
    rarity: 'legendary',
    cost: 6,
    attack: 4,
    health: 6,
    battlecry: { ops: [{ op: 'draw', count: 2 }] },
    text: { zh: '戰吼:抽兩張牌。未出茅廬,已知天下三分。', en: 'Battlecry: Draw 2 cards. He divided the realm in three before leaving his cottage.' },
  },
  'hist-sun-wu': {
    keywords: ['rush'],
    text: { zh: '突襲。其疾如風,侵掠如火。', en: 'Rush. Swift as wind, fierce as fire.' },
  },
  'hist-wei-qing': {
    keywords: ['rush'],
    text: { zh: '突襲。長平桓桓,直搗龍城。', en: 'Rush. He struck straight at Longcheng.' },
  },
  'hist-li-jing': {
    cost: 7,
    attack: 6,
    health: 7,
    keywords: ['rush'],
    text: { zh: '突襲。夜襲陰山,三千鐵騎定漠北。', en: 'Rush. Three thousand riders in the night settled the northern steppe.' },
  },
  'hist-guo-ziyi': {
    battlecry: { ops: [{ op: 'heal', amount: 5, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公5點生命。功蓋天下,再造唐室。', en: 'Battlecry: Restore 5 Health to your hero. He rebuilt the House of Tang.' },
  },
  'hist-tang-taizong': {
    attack: 7,
    health: 7,
    battlecry: {
      ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'friendlyDynastyGenerals' }],
      condition: { ifDynastyCount: { dynasty: 'tang', atLeast: 2 } },
    },
    text: { zh: '戰吼:若你控制至少2名唐勢力武將,友方唐勢力武將+2/+2。天可汗親臨。', en: 'Battlecry: If you control 2+ Tang generals, give your Tang generals +2/+2.' },
  },
  'hist-zhao-kuangyin': {
    attack: 6,
    health: 6,
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'self' }] },
    text: { zh: '戰吼:黃袍加身,自身+2/+2。陳橋一夜,天下易主。', en: 'Battlecry: Don the yellow robe — gain +2/+2.' },
  },
  'hist-yue-fei': {
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方宋勢力武將+2/+2。撼山易,撼岳家軍難。', en: 'Battlecry: Give your Song generals +2/+2. Easier to move a mountain than the Yue Family Army.' },
  },
  'hist-han-shizhong': {
    attack: 6,
    health: 8,
    keywords: ['guard'],
    text: { zh: '守護。黃天蕩上,八千銳卒扼十萬金軍。', en: 'Guard. At Huangtiandang, eight thousand held back a hundred thousand.' },
  },
  'hist-qi-jiguang': {
    attack: 6,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。鴛鴦陣成,倭寇喪膽。', en: 'Rush. The Mandarin Duck formation broke the wokou.' },
  },
  'hist-xu-da': {
    attack: 6,
    health: 7,
    keywords: ['charge'],
    text: { zh: '衝鋒。北伐中原,驅逐胡虜。', en: 'Charge. He marched north and reclaimed the Central Plains.' },
  },

  // ================= 霸道 hegemonic =================
  'cao-cao': {
    dynasty: 'wei',
    doctrine: 'hegemonic',
    attack: 6,
    health: 7,
    battlecry: { ops: [{ op: 'aoeDamage', amount: 1 }, { op: 'draw', count: 1 }] },
    text: { zh: '戰吼:對所有敵方武將造成1點傷害,抽一張牌。寧教我負天下人。', en: 'Battlecry: Deal 1 damage to all enemy generals and draw a card.' },
  },
  'xiahou-dun': {
    dynasty: 'wei',
    cost: 6,
    attack: 6,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。拔矢啖睛,父精母血不可棄。', en: 'Rush. He plucked out the arrow and swallowed his own eye.' },
  },
  'zhang-liao': {
    dynasty: 'wei',
    cost: 6,
    attack: 6,
    health: 6,
    keywords: ['charge'],
    text: { zh: '衝鋒。八百破十萬,威震逍遙津。', en: 'Charge. Eight hundred against a hundred thousand at Xiaoyao Ford.' },
  },
  'xu-chu': {
    dynasty: 'wei',
    doctrine: 'hegemonic',
    rarity: 'rare',
    attack: 6,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。虎癡裸衣鬥馬超。', en: 'Guard. The Tiger Fool fought Ma Chao bare-chested.' },
  },
  'pang-de': {
    dynasty: 'wei',
    attack: 7,
    health: 5,
    keywords: ['duel'],
    text: { zh: '單挑。抬櫬決死,義不受辱。', en: 'Duel. He carried his own coffin into battle.' },
  },
  'gao-shun': {
    dynasty: 'qun',
    keywords: ['charge'],
    text: { zh: '衝鋒。陷陣之志,有死無生。', en: 'Charge. The Camp Crushers know no retreat.' },
  },
  'ma-chao': {
    dynasty: 'shu',
    cost: 7,
    attack: 6,
    health: 6,
    keywords: ['charge', 'duel'],
    text: { zh: '衝鋒、單挑。錦馬超,西涼鐵騎;葭萌關下,挑燈夜戰。', en: 'Charge, Duel. The Splendid Ma Chao dueled Zhang Fei by torchlight at Jiameng Pass.' },
  },
  'hist-wu-qi': {
    attack: 6,
    health: 6,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方戰國勢力武將+1/+1。魏武卒,天下勁旅。', en: 'Battlecry: Give your Warring States generals +1/+1.' },
  },
  'hist-bai-qi': {
    cost: 9,
    battlecry: { ops: [{ op: 'destroy', target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:消滅一名敵方武將。長平之戰,人屠之名。', en: 'Battlecry: Destroy an enemy general. At Changping, the Butcher earned his name.' },
  },
  'hist-xiang-yu': {
    attack: 9,
    keywords: ['duel'],
    text: { zh: '單挑。力拔山兮氣蓋世。', en: 'Duel. His strength uprooted mountains; his spirit overshadowed the age.' },
  },
  'hist-han-xin': {
    attack: 5,
    health: 6,
    battlecry: {
      ops: [
        { op: 'draw', count: 1 },
        { op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' },
      ],
    },
    text: { zh: '戰吼:抽一張牌,友方楚漢勢力武將+1/+1。韓信點兵,多多益善。', en: 'Battlecry: Draw a card and give your Chu-Han generals +1/+1. The more, the better.' },
  },
  'hist-huo-qubing': {
    attack: 7,
    health: 6,
    keywords: ['charge'],
    text: { zh: '衝鋒。封狼居胥,匈奴遠遁。', en: 'Charge. He sealed Mount Langjuxu and the Xiongnu fled.' },
  },
  'hist-chang-yuchun': {
    attack: 7,
    health: 6,
    keywords: ['charge'],
    text: { zh: '衝鋒。自請十萬眾,橫行天下——人稱常十萬。', en: 'Charge. Give me a hundred thousand and I will sweep the realm.' },
  },
  'hist-lian-po': {
    attack: 6,
    health: 8,
    keywords: ['guard'],
    text: { zh: '守護。廉頗老矣,尚能飯否?', en: 'Guard. Old Lian Po can still eat — and still fight.' },
  },
  'hist-fan-kuai': {
    attack: 5,
    health: 7,
    keywords: ['guard'],
    text: { zh: '守護。鴻門宴上,持盾闖帳。', en: 'Guard. He burst into the Hongmen banquet, shield first.' },
  },

  // ================= 礼教 ritual =================
  'hist-confucius': {
    rarity: 'legendary',
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }, { op: 'draw', count: 1 }] },
    text: { zh: '戰吼:恢復我方主公3點生命,抽一張牌。克己復禮,有教無類。', en: 'Battlecry: Restore 3 Health to your hero and draw a card.' },
  },
  'xun-yu': {
    dynasty: 'wei',
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。王佐之才,居中持重。', en: 'Battlecry: Draw a card. A talent fit to aid kings.' },
  },
  'huang-zhong': {
    dynasty: 'shu',
    attack: 7,
    health: 5,
    keywords: ['duel'],
    text: { zh: '單挑。定軍山前,老當益壯。', en: 'Duel. At Mount Dingjun, age only sharpened his blade.' },
  },
  'hist-fan-zhongyan': {
    battlecry: { ops: [{ op: 'heal', amount: 4, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公4點生命。先天下之憂而憂。', en: 'Battlecry: Restore 4 Health to your hero. First to worry over the world’s worries.' },
  },
  'hist-bao-zheng': {
    cost: 5,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'damage', amount: 3, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成3點傷害。鍘刀之下,明正典刑。', en: 'Battlecry: Deal 3 damage to an enemy general. Justice falls like the blade.' },
  },
  'hist-yan-zhenqing': {
    keywords: ['guard'],
    text: { zh: '守護。忠義節烈,守土不移。', en: 'Guard. Loyal in life, unbending in death.' },
  },
  'hist-yu-qian': {
    keywords: ['guard'],
    text: { zh: '守護。粉身碎骨渾不怕,要留清白在人間。', en: 'Guard. Ground to dust, he feared nothing — only a stained name.' },
  },
  'hist-wang-shouren': {
    attack: 5,
    health: 6,
    battlecry: { ops: [{ op: 'draw', count: 2 }] },
    text: { zh: '戰吼:抽兩張牌。知行合一,此心光明。', en: 'Battlecry: Draw 2 cards. Knowledge and action are one.' },
  },

  // ================= 名利 fame =================
  'sima-yi': {
    dynasty: 'wei',
    battlecry: {
      ops: [{ op: 'draw', count: 2 }],
      condition: { ifDynastyCount: { dynasty: 'wei', atLeast: 2 } },
    },
    text: { zh: '戰吼:若你控制至少2名魏勢力武將,抽兩張牌。鷹視狼顧,隱忍待機。', en: 'Battlecry: If you control 2+ Wei generals, draw 2 cards.' },
  },
  'zhou-yu': {
    dynasty: 'wu',
    attack: 6,
    health: 6,
    battlecry: { ops: [{ op: 'damage', amount: 3, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成3點傷害。談笑間,檣櫓灰飛煙滅。', en: 'Battlecry: Deal 3 damage to an enemy general. Masts and oars turned to ash mid-laughter.' },
  },
  'lu-xun': {
    dynasty: 'wu',
    attack: 5,
    health: 6,
    battlecry: { ops: [{ op: 'aoeDamage', amount: 2 }] },
    text: { zh: '戰吼:對所有敵方武將造成2點傷害。火燒連營七百里。', en: 'Battlecry: Deal 2 damage to all enemy generals. Seven hundred li of camps aflame.' },
  },
  'guo-jia': {
    dynasty: 'wei',
    rarity: 'epic',
    attack: 4,
    health: 3,
    deathrattle: { ops: [{ op: 'draw', count: 2 }] },
    text: { zh: '遺計:抽兩張牌。郭嘉遺計定遼東。', en: 'Deathrattle: Draw 2 cards. His final stratagem settled Liaodong.' },
  },
  'jia-xu': {
    dynasty: 'wei',
    attack: 5,
    health: 5,
    battlecry: { ops: [{ op: 'damage', amount: 2, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成2點傷害。毒士一計,天下大亂。', en: 'Battlecry: Deal 2 damage to an enemy general. One scheme from the Poison Sage upended the realm.' },
  },
  'diaochan': {
    dynasty: 'qun',
    rarity: 'epic',
    cost: 4,
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'damage', amount: 3, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成3點傷害。連環離間,借刀殺人。', en: 'Battlecry: Deal 3 damage to an enemy general. A borrowed blade, guided by beauty.' },
  },
  'zhang-jiao': {
    dynasty: 'qun',
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'aoeDamage', amount: 1 }, { op: 'heal', amount: 2, target: 'friendlyHero' }] },
    text: { zh: '戰吼:對所有敵方武將造成1點傷害,恢復我方主公2點生命。蒼天已死,黃天當立。', en: 'Battlecry: Deal 1 damage to all enemy generals; restore 2 Health to your hero.' },
  },
  'hist-su-qin': {
    attack: 4,
    health: 3,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。佩六國相印,合縱抗秦。', en: 'Battlecry: Draw a card. He wore the seals of six states.' },
  },
  'hist-jing-ke': {
    rarity: 'epic',
    cost: 4,
    attack: 4,
    health: 2,
    battlecry: { ops: [{ op: 'damage', amount: 4, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成4點傷害。圖窮匕見,一擊而已。', en: 'Battlecry: Deal 4 damage to an enemy general. The map unrolls; the dagger appears.' },
  },

  // ================= 割据 separatist =================
  'sun-quan': {
    dynasty: 'wu',
    doctrine: 'separatist',
    battlecry: {
      ops: [{ op: 'draw', count: 2 }],
      condition: { ifDynastyCount: { dynasty: 'wu', atLeast: 2 } },
    },
    text: { zh: '戰吼:若你控制至少2名吳勢力武將,抽兩張牌。生子當如孫仲謀,坐斷東南戰未休。', en: 'Battlecry: If you control 2+ Wu generals, draw 2 cards.' },
  },
  'sun-ce': {
    dynasty: 'wu',
    doctrine: 'separatist',
    rarity: 'legendary',
    cost: 6,
    attack: 6,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。小霸王橫掃江東,六郡傳檄而定。', en: 'Charge. The Little Conqueror swept the Southland.' },
  },
  'taishi-ci': {
    dynasty: 'wu',
    doctrine: 'separatist',
    attack: 6,
    health: 5,
    keywords: ['duel'],
    text: { zh: '單挑。神亭嶺上,與小霸王酣戰百合。', en: 'Duel. He traded a hundred blows with Sun Ce at Shenting.' },
  },
  'lu-meng': {
    dynasty: 'wu',
    doctrine: 'separatist',
    attack: 5,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。白衣渡江,兵不血刃取荊州。', en: 'Rush. In white robes he crossed the river and took Jingzhou without a fight.' },
  },
  'gan-ning': {
    dynasty: 'wu',
    doctrine: 'separatist',
    rarity: 'epic',
    attack: 4,
    health: 5,
    keywords: ['charge'],
    battlecry: { ops: [{ op: 'aoeDamage', amount: 1 }] },
    text: { zh: '衝鋒。戰吼:對所有敵方武將造成1點傷害。百騎劫魏營,錦帆賊之名震天下。', en: 'Charge. Battlecry: Deal 1 damage to all enemy generals. A hundred riders raided the Wei camp.' },
  },
  'dong-zhuo': {
    dynasty: 'qun',
    doctrine: 'separatist',
    rarity: 'epic',
    cost: 7,
    attack: 7,
    health: 8,
    battlecry: { ops: [{ op: 'damage', amount: 2, target: 'friendlyHero' }] },
    text: { zh: '戰吼:對我方主公造成2點傷害。暴虐無道,天下共怨。', en: 'Battlecry: Deal 2 damage to your own hero. His tyranny bled friend and foe alike.' },
  },
  'yuan-shao': {
    dynasty: 'qun',
    attack: 4,
    health: 6,
    battlecry: {
      ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }],
      condition: { ifDynastyCount: { dynasty: 'qun', atLeast: 2 } },
    },
    text: { zh: '戰吼:若你控制至少2名群勢力武將,友方群勢力武將+1/+1。四世三公,門生故吏遍天下。', en: 'Battlecry: If you control 2+ Qun generals, give your Qun generals +1/+1.' },
  },
  'meng-huo': {
    dynasty: 'qun',
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 7,
    attack: 5,
    health: 6,
    deathrattle: { ops: [{ op: 'summon', defId: 'zhu-rong', count: 1 }] },
    text: { zh: '遺計:召喚祝融夫人。七擒七縱終不悔,蠻王身後有蠻后。', en: 'Deathrattle: Summon Lady Zhurong. Captured seven times — avenged once.' },
  },
  'hist-li-cunxiao': {
    keywords: ['duel'],
    text: { zh: '單挑。王不過項,將不過李。', en: 'Duel. No king surpassed Xiang Yu; no general surpassed Li Cunxiao.' },
  },
  'hist-an-lushan': {
    attack: 6,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。漁陽鼙鼓動地來。', en: 'Charge. The war drums of Yuyang shook the earth.' },
  },

  // ================= 隐逸 reclusion =================
  // 隐逸卡池极薄(生成层仅17张),以下将方士/神医/隐士从中立改判入隐逸。
  'hist-laozi': {
    rarity: 'legendary',
    cost: 5,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 4, target: 'friendlyHero' }, { op: 'draw', count: 1 }] },
    text: { zh: '戰吼:恢復我方主公4點生命,抽一張牌。上善若水,道法自然。', en: 'Battlecry: Restore 4 Health to your hero and draw a card. The highest good is like water.' },
  },
  'hist-zhuangzi': {
    rarity: 'epic',
    cost: 5,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 2 }] },
    text: { zh: '戰吼:抽兩張牌。不知周之夢為蝴蝶與,蝴蝶之夢為周與?', en: 'Battlecry: Draw 2 cards. Was it Zhuang dreaming the butterfly, or the butterfly dreaming Zhuang?' },
  },
  'zuo-ci': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    attack: 3,
    health: 2,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。擲杯戲曹,幻化無窮。', en: 'Battlecry: Draw a card. He mocked Cao Cao with conjured cups.' },
  },
  'yu-ji': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    attack: 2,
    health: 4,
    deathrattle: { ops: [{ op: 'damage', amount: 3, target: 'randomEnemyGeneral' }] },
    text: { zh: '遺計:對一名隨機敵方武將造成3點傷害。怨魂不散,索命江東。', en: 'Deathrattle: Deal 3 damage to a random enemy general. His vengeful ghost haunted Sun Ce to death.' },
  },
  'hua-tuo': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    attack: 2,
    health: 3,
    battlecry: { ops: [{ op: 'heal', amount: 4, target: 'chosenAny' }] },
    text: { zh: '戰吼:恢復一個角色4點生命。刮骨療毒,妙手回春。', en: 'Battlecry: Restore 4 Health to a character. He scraped poison from the bone.' },
  },
  'sima-hui': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    attack: 2,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。水鏡先生,坐薦臥龍鳳雛。', en: 'Battlecry: Draw a card. Master Water-Mirror pointed the way to the Sleeping Dragon.' },
  },
  'hist-tao-yuanming': {
    attack: 3,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。采菊東籬下,悠然見南山。', en: 'Battlecry: Restore 3 Health to your hero. Picking chrysanthemums by the eastern fence.' },
  },
  'ji-kang': {
    dynasty: 'qun',
    deathrattle: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '遺計:抽一張牌。《廣陵散》於今絕矣。', en: 'Deathrattle: Draw a card. Guangling San dies with him.' },
  },
  'xu-shu': {
    dynasty: 'qun',
    keywords: ['guard'],
    text: { zh: '守護。身在曹營心在漢,一言不發亦護主。', en: 'Guard. In Cao’s camp, his heart stayed with Han — silent, but steadfast.' },
  },
  'hist-li-bai': {
    attack: 4,
    health: 4,
    keywords: ['windfury'],
    text: { zh: '連擊。十步殺一人,千里不留行。', en: 'Windfury. A kill every ten paces, no trace for a thousand li.' },
  },
  'hist-guiguzi': {
    doctrine: 'reclusion',
    cost: 5,
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'chosenAny' }] },
    text: { zh: '戰吼:使一名武將+2/+2。鬼谷授徒,出將入相。', en: 'Battlecry: Give a general +2/+2. His students became generals and chancellors.' },
  },

  // ================= 中立签名(简单关键词) =================
  'lu-bu': {
    dynasty: 'qun',
    rarity: 'legendary',
    cost: 8,
    attack: 10,
    health: 6,
    keywords: ['duel'],
    text: { zh: '單挑。人中呂布,馬中赤兔。', en: 'Duel. Among men, Lu Bu; among horses, Red Hare.' },
  },
  'dian-wei': {
    dynasty: 'wei',
    attack: 6,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。古之惡來,死守轅門。', en: 'Guard. The Evil Comes of old held the gate to his death.' },
  },
  'hua-xiong': {
    dynasty: 'qun',
    cost: 5,
    attack: 6,
    health: 4,
    keywords: ['duel'],
    text: { zh: '單挑。汜水關前連斬上將——直到那杯酒尚溫。', en: 'Duel. He felled champion after champion — until the wine was still warm.' },
  },
  'yan-liang': {
    dynasty: 'qun',
    attack: 6,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。河北名將,先聲奪人。', en: 'Charge. Hebei’s champion strikes first.' },
  },
  'wen-chou': {
    dynasty: 'qun',
    attack: 6,
    health: 5,
    keywords: ['rush'],
    text: { zh: '突襲。延津突騎,爭先赴敵。', en: 'Rush. The shock riders of Yanjin.' },
  },
  'zhou-tai': {
    dynasty: 'wu',
    attack: 5,
    health: 7,
    keywords: ['guard'],
    text: { zh: '守護。渾身刀痕,護主周全。', en: 'Guard. Every scar a debt repaid.' },
  },
  'huang-gai': {
    dynasty: 'wu',
    attack: 5,
    health: 6,
    keywords: ['charge'],
    text: { zh: '衝鋒。火船衝陣,苦肉建功。', en: 'Charge. Fire ships ram the line.' },
  },
  'ding-feng': {
    dynasty: 'wu',
    attack: 6,
    health: 5,
    keywords: ['rush'],
    text: { zh: '突襲。雪中奮短兵。', en: 'Rush. Short blades in the snow.' },
  },
  'wei-yan': {
    dynasty: 'shu',
    attack: 6,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。子午谷奇謀未售,先登陷陣有餘。', en: 'Charge. His Ziwu Valley gambit was refused — his vanguard never was.' },
  },
  'liao-hua': {
    dynasty: 'shu',
    keywords: ['rush'],
    text: { zh: '突襲。蜀中無大將,廖化作先鋒。', en: 'Rush. When Shu ran out of great generals, Liao Hua led the van.' },
  },
  'chen-dao': {
    dynasty: 'shu',
    attack: 5,
    health: 7,
    keywords: ['guard'],
    text: { zh: '守護。白毦精兵,護衛中軍。', en: 'Guard. The White Feather Guard shields the center.' },
  },
  'ma-dai': {
    dynasty: 'shu',
    cost: 5,
    attack: 5,
    health: 5,
    keywords: ['rush'],
    text: { zh: '突襲。陣前一刀,襲斬魏延。', en: 'Rush. One stroke from behind ended Wei Yan.' },
  },
}
