import type { CardDef } from '../../engine/types'

// 签名卡手工调校层:覆盖生成公式的默认值。
// 键 = 武将 id(与姊妹仓库一致,必须存在于 cards.gen.ts)。这里只放与生成值不同的字段。
// 设计基线:白板曲线 总身材 ≈ cost*2+1,关键词与效果按约 1~2 点身材/费计价。
// 关键词译名:衝鋒 charge / 突襲 rush / 守護 guard / 連擊 windfury / 單挑 duel。
export const SIGNATURE_OVERRIDES: Record<string, Partial<CardDef>> = {
  // ================= 王道 royal =================
  'liu-bei': {
    dynasty: 'shu',
    doctrine: 'royal',
    cost: 6,
    attack: 5,
    health: 6,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方蜀勢力武將+1/+1。仁德載世,三顧乃見。', en: 'Battlecry: Give your Shu generals +1/+1.' },
  },
  'guan-yu': {
    dynasty: 'shu',
    doctrine: 'royal',
    rarity: 'legendary',
    cost: 7,
    attack: 7,
    health: 7,
    keywords: ['duel'],
    text: { zh: '單挑。溫酒斬將,千里走單騎。', en: 'Duel. The Saint of War rides a thousand li alone.' },
  },
  'zhang-fei': {
    dynasty: 'shu',
    doctrine: 'royal',
    rarity: 'epic',
    cost: 6,
    attack: 6,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。當陽橋頭一聲吼,喝斷橋樑水倒流。', en: 'Guard. One roar at Changban Bridge turned the river back.' },
  },
  'zhao-yun': {
    dynasty: 'shu',
    doctrine: 'royal',
    cost: 7,
    attack: 6,
    health: 6,
    keywords: ['charge'],
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '衝鋒。戰吼:抽一張牌。長坂單騎救主,懷抱幼主而還。', en: 'Charge. Battlecry: Draw a card. He rode alone through Changban and returned with the young lord.' },
  },
  'zhuge-liang': {
    dynasty: 'shu',
    doctrine: 'royal',
    rarity: 'legendary',
    cost: 6,
    attack: 4,
    health: 6,
    battlecry: { ops: [{ op: 'draw', count: 2 }] },
    text: { zh: '戰吼:抽兩張牌。未出茅廬,已知天下三分。', en: 'Battlecry: Draw 2 cards. He divided the realm in three before leaving his cottage.' },
  },
  'hist-sun-wu': {
    keywords: ['rush'],
    text: { zh: '突襲。其疾如風,侵掠如火。', en: 'Rush. Swift as wind, fierce as fire.' },
  },
  'hist-wei-qing': {
    keywords: ['rush'],
    text: { zh: '突襲。長平桓桓,直搗龍城。', en: 'Rush. He struck straight at Longcheng.' },
  },
  'hist-li-jing': {
    cost: 7,
    attack: 6,
    health: 7,
    keywords: ['rush'],
    text: { zh: '突襲。夜襲陰山,三千鐵騎定漠北。', en: 'Rush. Three thousand riders in the night settled the northern steppe.' },
  },
  'hist-guo-ziyi': {
    battlecry: { ops: [{ op: 'heal', amount: 5, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公5點生命。功蓋天下,再造唐室。', en: 'Battlecry: Restore 5 Health to your hero. He rebuilt the House of Tang.' },
  },
  'hist-tang-taizong': {
    attack: 7,
    health: 7,
    battlecry: {
      ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'friendlyDynastyGenerals' }],
      condition: { ifDynastyCount: { dynasty: 'tang', atLeast: 2 } },
    },
    text: { zh: '戰吼:若你控制至少2名唐勢力武將,友方唐勢力武將+2/+2。天可汗親臨。', en: 'Battlecry: If you control 2+ Tang generals, give your Tang generals +2/+2.' },
  },
  'hist-zhao-kuangyin': {
    attack: 6,
    health: 6,
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'self' }] },
    text: { zh: '戰吼:黃袍加身,自身+2/+2。陳橋一夜,天下易主。', en: 'Battlecry: Don the yellow robe — gain +2/+2.' },
  },
  'hist-yue-fei': {
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方宋勢力武將+2/+2。撼山易,撼岳家軍難。', en: 'Battlecry: Give your Song generals +2/+2. Easier to move a mountain than the Yue Family Army.' },
  },
  'hist-han-shizhong': {
    attack: 6,
    health: 8,
    keywords: ['guard'],
    text: { zh: '守護。黃天蕩上,八千銳卒扼十萬金軍。', en: 'Guard. At Huangtiandang, eight thousand held back a hundred thousand.' },
  },
  'hist-qi-jiguang': {
    attack: 6,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。鴛鴦陣成,倭寇喪膽。', en: 'Rush. The Mandarin Duck formation broke the wokou.' },
  },
  'hist-xu-da': {
    attack: 6,
    health: 7,
    keywords: ['charge'],
    text: { zh: '衝鋒。北伐中原,驅逐胡虜。', en: 'Charge. He marched north and reclaimed the Central Plains.' },
  },
  'hist-wang-jian': {
    attack: 7,
    health: 8,
    keywords: ['guard'],
    text: { zh: '守護。滅五國者,王翦父子;非六十萬人不可。', en: 'Guard. Five of the six states fell to Wang Jian and his son — and he never marched with fewer than six hundred thousand.' },
  },
  'hist-meng-tian': {
    attack: 6,
    health: 8,
    keywords: ['guard'],
    text: { zh: '守護。北築長城,卻匈奴七百餘里。', en: 'Guard. He raised the Great Wall and drove the Xiongnu seven hundred li north.' },
  },
  'hist-zhang-liang': {
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。運籌帷幄之中,決勝千里之外。', en: 'Battlecry: Draw a card. Plans laid within the tent decide victory a thousand li away.' },
  },
  'hist-xiao-he': {
    attack: 3,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。鎮國撫民,饋餉不絕;月下追還韓信。', en: 'Battlecry: Restore 3 Health to your hero. He kept the state fed — and chased Han Xin back by moonlight.' },
  },
  'hist-liu-xiu': {
    cost: 6,
    attack: 5,
    health: 7,
    battlecry: {
      ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'friendlyDynastyGenerals' }],
      condition: { ifDynastyCount: { dynasty: 'western-han', atLeast: 2 } },
    },
    text: { zh: '戰吼:若你控制至少2名漢勢力武將,友方漢勢力武將+2/+2。昆陽大風,雲台諸將。', en: 'Battlecry: If you control 2+ Han generals, give your Han generals +2/+2. The storm at Kunyang; the generals of Cloud Terrace.' },
  },
  'hist-ban-chao': {
    attack: 6,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。不入虎穴,焉得虎子。投筆從戎,萬里封侯。', en: 'Rush. Into the tiger’s den for the tiger’s cub — he traded the brush for the sword.' },
  },
  'hist-zu-ti': {
    cost: 5,
    attack: 5,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。聞雞起舞,中流擊楫:不清中原者,有如大江!', en: 'Charge. He drilled at cockcrow and struck his oar mid-river: the Central Plains, or this river bears witness.' },
  },
  'hist-xie-xuan': {
    attack: 6,
    health: 6,
    battlecry: { ops: [{ op: 'aoeDamage', amount: 1 }] },
    text: { zh: '戰吼:對所有敵方武將造成1點傷害。淝水一戰,風聲鶴唳,草木皆兵。', en: 'Battlecry: Deal 1 damage to all enemy generals. After Feishui, every wind and crane cry sounded like pursuit.' },
  },
  'hist-wen-tianxiang': {
    attack: 4,
    health: 5,
    keywords: ['guard'],
    deathrattle: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '守護。遺計:抽一張牌。人生自古誰無死,留取丹心照汗青。', en: 'Guard. Deathrattle: Draw a card. All men must die — let this loyal heart shine in the annals.' },
  },
  'hist-zheng-chenggong': {
    attack: 6,
    health: 6,
    keywords: ['charge'],
    text: { zh: '衝鋒。驅逐紅夷,復我台灣;海上孤忠,延平王旗。', en: 'Charge. He drove out the Dutch and took back Taiwan under the lone banner of Yanping.' },
  },

  // ================= 霸道 hegemonic =================
  'cao-cao': {
    dynasty: 'wei',
    doctrine: 'hegemonic',
    attack: 6,
    health: 7,
    battlecry: { ops: [{ op: 'aoeDamage', amount: 1 }, { op: 'draw', count: 1 }] },
    text: { zh: '戰吼:對所有敵方武將造成1點傷害,抽一張牌。寧教我負天下人。', en: 'Battlecry: Deal 1 damage to all enemy generals and draw a card.' },
  },
  'xiahou-dun': {
    dynasty: 'wei',
    cost: 6,
    attack: 6,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。拔矢啖睛,父精母血不可棄。', en: 'Rush. He plucked out the arrow and swallowed his own eye.' },
  },
  'zhang-liao': {
    dynasty: 'wei',
    cost: 6,
    attack: 6,
    health: 6,
    keywords: ['charge'],
    text: { zh: '衝鋒。八百破十萬,威震逍遙津。', en: 'Charge. Eight hundred against a hundred thousand at Xiaoyao Ford.' },
  },
  'xu-chu': {
    dynasty: 'wei',
    doctrine: 'hegemonic',
    rarity: 'rare',
    attack: 6,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。虎癡裸衣鬥馬超。', en: 'Guard. The Tiger Fool fought Ma Chao bare-chested.' },
  },
  'pang-de': {
    dynasty: 'wei',
    attack: 7,
    health: 5,
    keywords: ['duel'],
    text: { zh: '單挑。抬櫬決死,義不受辱。', en: 'Duel. He carried his own coffin into battle.' },
  },
  'gao-shun': {
    dynasty: 'qun',
    keywords: ['charge'],
    text: { zh: '衝鋒。陷陣之志,有死無生。', en: 'Charge. The Camp Crushers know no retreat.' },
  },
  'ma-chao': {
    dynasty: 'shu',
    cost: 7,
    attack: 6,
    health: 6,
    keywords: ['charge', 'duel'],
    text: { zh: '衝鋒、單挑。錦馬超,西涼鐵騎;葭萌關下,挑燈夜戰。', en: 'Charge, Duel. The Splendid Ma Chao dueled Zhang Fei by torchlight at Jiameng Pass.' },
  },
  'hist-wu-qi': {
    attack: 6,
    health: 6,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方戰國勢力武將+1/+1。魏武卒,天下勁旅。', en: 'Battlecry: Give your Warring States generals +1/+1.' },
  },
  'hist-bai-qi': {
    cost: 9,
    battlecry: { ops: [{ op: 'destroy', target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:消滅一名敵方武將。長平之戰,人屠之名。', en: 'Battlecry: Destroy an enemy general. At Changping, the Butcher earned his name.' },
  },
  'hist-xiang-yu': {
    attack: 9,
    keywords: ['duel'],
    text: { zh: '單挑。力拔山兮氣蓋世。', en: 'Duel. His strength uprooted mountains; his spirit overshadowed the age.' },
  },
  'hist-han-xin': {
    attack: 5,
    health: 6,
    battlecry: {
      ops: [
        { op: 'draw', count: 1 },
        { op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' },
      ],
    },
    text: { zh: '戰吼:抽一張牌,友方楚漢勢力武將+1/+1。韓信點兵,多多益善。', en: 'Battlecry: Draw a card and give your Chu-Han generals +1/+1. The more, the better.' },
  },
  'hist-huo-qubing': {
    attack: 7,
    health: 6,
    keywords: ['charge'],
    text: { zh: '衝鋒。封狼居胥,匈奴遠遁。', en: 'Charge. He sealed Mount Langjuxu and the Xiongnu fled.' },
  },
  'hist-chang-yuchun': {
    attack: 7,
    health: 6,
    keywords: ['charge'],
    text: { zh: '衝鋒。自請十萬眾,橫行天下——人稱常十萬。', en: 'Charge. Give me a hundred thousand and I will sweep the realm.' },
  },
  'hist-lian-po': {
    attack: 6,
    health: 8,
    keywords: ['guard'],
    text: { zh: '守護。廉頗老矣,尚能飯否?', en: 'Guard. Old Lian Po can still eat — and still fight.' },
  },
  'hist-fan-kuai': {
    attack: 5,
    health: 7,
    keywords: ['guard'],
    text: { zh: '守護。鴻門宴上,持盾闖帳。', en: 'Guard. He burst into the Hongmen banquet, shield first.' },
  },
  'hist-li-mu': {
    attack: 6,
    health: 8,
    keywords: ['rush'],
    text: { zh: '突襲。雁門設伏,一戰破匈奴十萬騎。李牧死,趙國亡。', en: 'Rush. His ambush at Yanmen broke a hundred thousand riders. When Li Mu died, Zhao followed.' },
  },
  'hist-li-guang': {
    cost: 6,
    attack: 6,
    health: 5,
    keywords: ['duel'],
    text: { zh: '單挑。但使龍城飛將在,不教胡馬度陰山。', en: 'Duel. While the Flying General stands, no nomad horse crosses the Yin Mountains.' },
  },
  'hist-zhou-yafu': {
    attack: 5,
    health: 8,
    keywords: ['guard'],
    text: { zh: '守護。細柳營中,但聞將軍令,不聞天子詔。', en: 'Guard. In the Willow Camp, the general’s order outranked the emperor’s edict.' },
  },
  'hist-qin-qiong': {
    cost: 6,
    attack: 6,
    health: 6,
    keywords: ['duel'],
    text: { zh: '單挑。馬踏黃河兩岸,鐧打三州六府。', en: 'Duel. His twin mauls kept order on both banks of the Yellow River.' },
  },
  'hist-yuchi-gong': {
    attack: 6,
    health: 8,
    keywords: ['guard'],
    text: { zh: '守護。單鞭奪槊,夜守宮門,邪祟辟易。', en: 'Guard. With a bare whip he seized lances; demons flee the gate he keeps.' },
  },
  'hist-xue-rengui': {
    attack: 6,
    health: 6,
    battlecry: { ops: [{ op: 'damage', amount: 3, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成3點傷害。將軍三箭定天山,壯士長歌入漢關。', en: 'Battlecry: Deal 3 damage to an enemy general. Three arrows settled Heaven Mountain.' },
  },
  'hist-su-dingfang': {
    attack: 7,
    health: 6,
    keywords: ['charge'],
    text: { zh: '衝鋒。前後滅三國,皆生擒其主。', en: 'Charge. He toppled three kingdoms and took each of their rulers alive.' },
  },
  'hist-di-qing': {
    cost: 6,
    attack: 6,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。銅面披髮,夜奪崑崙關。', en: 'Rush. Bronze-masked, hair loose, he stormed Kunlun Pass by night.' },
  },
  'hist-lan-yu': {
    attack: 7,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。深入漠北,搗虜庭於捕魚兒海。', en: 'Rush. He smashed the horde’s court at Lake Buir.' },
  },
  'hist-yu-dayou': {
    cost: 6,
    attack: 7,
    health: 5,
    keywords: ['duel'],
    text: { zh: '單挑。俞龍戚虎,劍術冠絕當世。', en: 'Duel. The Dragon Yu — no blade of his age could match his.' },
  },

  // ================= 礼教 ritual =================
  'hist-confucius': {
    rarity: 'legendary',
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }, { op: 'draw', count: 1 }] },
    text: { zh: '戰吼:恢復我方主公3點生命,抽一張牌。克己復禮,有教無類。', en: 'Battlecry: Restore 3 Health to your hero and draw a card.' },
  },
  'xun-yu': {
    dynasty: 'wei',
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。王佐之才,居中持重。', en: 'Battlecry: Draw a card. A talent fit to aid kings.' },
  },
  'huang-zhong': {
    dynasty: 'shu',
    attack: 7,
    health: 5,
    keywords: ['duel'],
    text: { zh: '單挑。定軍山前,老當益壯。', en: 'Duel. At Mount Dingjun, age only sharpened his blade.' },
  },
  'hist-fan-zhongyan': {
    battlecry: { ops: [{ op: 'heal', amount: 4, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公4點生命。先天下之憂而憂。', en: 'Battlecry: Restore 4 Health to your hero. First to worry over the world’s worries.' },
  },
  'hist-bao-zheng': {
    cost: 5,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'damage', amount: 3, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成3點傷害。鍘刀之下,明正典刑。', en: 'Battlecry: Deal 3 damage to an enemy general. Justice falls like the blade.' },
  },
  'hist-yan-zhenqing': {
    keywords: ['guard'],
    text: { zh: '守護。忠義節烈,守土不移。', en: 'Guard. Loyal in life, unbending in death.' },
  },
  'hist-yu-qian': {
    keywords: ['guard'],
    text: { zh: '守護。粉身碎骨渾不怕,要留清白在人間。', en: 'Guard. Ground to dust, he feared nothing — only a stained name.' },
  },
  'hist-wang-shouren': {
    attack: 5,
    health: 6,
    battlecry: { ops: [{ op: 'draw', count: 2 }] },
    text: { zh: '戰吼:抽兩張牌。知行合一,此心光明。', en: 'Battlecry: Draw 2 cards. Knowledge and action are one.' },
  },
  'hist-mencius': {
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'chosenAny' }] },
    text: { zh: '戰吼:使一名武將+2/+2。吾善養吾浩然之氣。', en: 'Battlecry: Give a general +2/+2. I nourish my flood-like qi.' },
  },
  'hist-xunzi': {
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。青,取之於藍,而青於藍。', en: 'Battlecry: Draw a card. Blue is born of indigo, yet bluer still.' },
  },
  'hist-wei-zheng': {
    doctrine: 'ritual',
    attack: 3,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。以人為鏡,可以明得失。', en: 'Battlecry: Restore 3 Health to your hero. A man for a mirror shows gain and loss.' },
  },
  'hist-han-yu': {
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'damage', amount: 2, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成2點傷害。一篇祭文,惡溪之鱷遠徙六十里。', en: 'Battlecry: Deal 2 damage to an enemy general. One proclamation drove the crocodiles sixty li downriver.' },
  },
  'hist-sima-guang': {
    attack: 3,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'chosenAny' }] },
    text: { zh: '戰吼:恢復一個角色3點生命。破甕救友,臨大事而不亂。', en: 'Battlecry: Restore 3 Health to a character. He smashed the vat and saved his friend.' },
  },
  'hist-zhu-xi': {
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方宋勢力武將+1/+1。問渠那得清如許?為有源頭活水來。', en: 'Battlecry: Give your Song generals +1/+1. The channel runs clear because living water feeds it.' },
  },
  'hist-yu-yunwen': {
    doctrine: 'ritual',
    attack: 4,
    health: 6,
    battlecry: { ops: [{ op: 'damage', amount: 2, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成2點傷害。采石一戰,書生卻虜十萬。', en: 'Battlecry: Deal 2 damage to an enemy general. At Caishi, one scholar turned back a hundred thousand.' },
  },
  'hist-zeng-guofan': {
    attack: 4,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。結硬寨,打呆仗,湘軍之律。', en: 'Guard. Build iron camps; fight patient battles — the law of the Xiang Army.' },
  },

  // ================= 名利 fame =================
  'sima-yi': {
    dynasty: 'wei',
    battlecry: {
      ops: [{ op: 'draw', count: 2 }],
      condition: { ifDynastyCount: { dynasty: 'wei', atLeast: 2 } },
    },
    text: { zh: '戰吼:若你控制至少2名魏勢力武將,抽兩張牌。鷹視狼顧,隱忍待機。', en: 'Battlecry: If you control 2+ Wei generals, draw 2 cards.' },
  },
  'zhou-yu': {
    dynasty: 'wu',
    attack: 6,
    health: 6,
    battlecry: { ops: [{ op: 'damage', amount: 3, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成3點傷害。談笑間,檣櫓灰飛煙滅。', en: 'Battlecry: Deal 3 damage to an enemy general. Masts and oars turned to ash mid-laughter.' },
  },
  'lu-xun': {
    dynasty: 'wu',
    attack: 5,
    health: 6,
    battlecry: { ops: [{ op: 'aoeDamage', amount: 2 }] },
    text: { zh: '戰吼:對所有敵方武將造成2點傷害。火燒連營七百里。', en: 'Battlecry: Deal 2 damage to all enemy generals. Seven hundred li of camps aflame.' },
  },
  'guo-jia': {
    dynasty: 'wei',
    rarity: 'epic',
    attack: 4,
    health: 3,
    deathrattle: { ops: [{ op: 'draw', count: 2 }] },
    text: { zh: '遺計:抽兩張牌。郭嘉遺計定遼東。', en: 'Deathrattle: Draw 2 cards. His final stratagem settled Liaodong.' },
  },
  'jia-xu': {
    dynasty: 'wei',
    attack: 5,
    health: 5,
    battlecry: { ops: [{ op: 'damage', amount: 2, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成2點傷害。毒士一計,天下大亂。', en: 'Battlecry: Deal 2 damage to an enemy general. One scheme from the Poison Sage upended the realm.' },
  },
  'diaochan': {
    dynasty: 'qun',
    rarity: 'epic',
    cost: 4,
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'damage', amount: 3, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成3點傷害。連環離間,借刀殺人。', en: 'Battlecry: Deal 3 damage to an enemy general. A borrowed blade, guided by beauty.' },
  },
  'zhang-jiao': {
    dynasty: 'qun',
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'aoeDamage', amount: 1 }, { op: 'heal', amount: 2, target: 'friendlyHero' }] },
    text: { zh: '戰吼:對所有敵方武將造成1點傷害,恢復我方主公2點生命。蒼天已死,黃天當立。', en: 'Battlecry: Deal 1 damage to all enemy generals; restore 2 Health to your hero.' },
  },
  'hist-su-qin': {
    attack: 4,
    health: 3,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。佩六國相印,合縱抗秦。', en: 'Battlecry: Draw a card. He wore the seals of six states.' },
  },
  'hist-jing-ke': {
    rarity: 'epic',
    cost: 4,
    attack: 4,
    health: 2,
    battlecry: { ops: [{ op: 'damage', amount: 4, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成4點傷害。圖窮匕見,一擊而已。', en: 'Battlecry: Deal 4 damage to an enemy general. The map unrolls; the dagger appears.' },
  },
  'hist-guan-zhong': {
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'draw', count: 2 }] },
    text: { zh: '戰吼:抽兩張牌。九合諸侯,一匡天下,管仲之謀也。', en: 'Battlecry: Draw 2 cards. Nine times he gathered the lords and set the realm aright.' },
  },
  'hist-zhang-yi': {
    attack: 4,
    health: 3,
    battlecry: { ops: [{ op: 'damage', amount: 2, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成2點傷害。以三寸之舌,戲諸侯於股掌。', en: 'Battlecry: Deal 2 damage to an enemy general. A three-inch tongue toyed with kings.' },
  },
  'hist-fan-ju': {
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。遠交近攻,秦並天下之策。', en: 'Battlecry: Draw a card. Befriend the far, strike the near — the strategy that won Qin the world.' },
  },
  'hist-li-si': {
    doctrine: 'fame',
    attack: 2,
    health: 4,
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'self' }] },
    text: { zh: '戰吼:自身+2/+2。倉中之鼠與廁中之鼠,在所自處耳。', en: 'Battlecry: Gain +2/+2. A rat in the granary, a rat in the privy — position is everything.' },
  },
  'hist-mao-sui': {
    doctrine: 'fame',
    attack: 4,
    health: 4,
    keywords: ['charge'],
    text: { zh: '衝鋒。錐處囊中,其末立見;按劍歷階,直上殿前。', en: 'Charge. An awl in a sack shows its point — sword in hand, he mounted the dais uninvited.' },
  },
  'pang-tong': {
    dynasty: 'shu',
    rarity: 'epic',
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'aoeDamage', amount: 1 }] },
    text: { zh: '戰吼:對所有敵方武將造成1點傷害。連環計成,鐵索連舟,只欠東風。', en: 'Battlecry: Deal 1 damage to all enemy generals. The chained ships waited only for the east wind.' },
  },
  'fa-zheng': {
    dynasty: 'shu',
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'damage', amount: 2, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成2點傷害。一飯之德必償,睚眥之怨必報。', en: 'Battlecry: Deal 2 damage to an enemy general. Every kindness repaid; every slight avenged.' },
  },
  'hist-yang-su': {
    attack: 6,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。先驅陷陣,卻者立斬,楊素未嘗敗北。', en: 'Rush. The vanguard broke the line or died retreating — Yang Su never lost.' },
  },

  // ================= 割据 separatist =================
  'sun-quan': {
    dynasty: 'wu',
    doctrine: 'separatist',
    battlecry: {
      ops: [{ op: 'draw', count: 2 }],
      condition: { ifDynastyCount: { dynasty: 'wu', atLeast: 2 } },
    },
    text: { zh: '戰吼:若你控制至少2名吳勢力武將,抽兩張牌。生子當如孫仲謀,坐斷東南戰未休。', en: 'Battlecry: If you control 2+ Wu generals, draw 2 cards.' },
  },
  'sun-ce': {
    dynasty: 'wu',
    doctrine: 'separatist',
    rarity: 'legendary',
    cost: 6,
    attack: 6,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。小霸王橫掃江東,六郡傳檄而定。', en: 'Charge. The Little Conqueror swept the Southland.' },
  },
  'taishi-ci': {
    dynasty: 'wu',
    doctrine: 'separatist',
    attack: 6,
    health: 5,
    keywords: ['duel'],
    text: { zh: '單挑。神亭嶺上,與小霸王酣戰百合。', en: 'Duel. He traded a hundred blows with Sun Ce at Shenting.' },
  },
  'lu-meng': {
    dynasty: 'wu',
    doctrine: 'separatist',
    attack: 5,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。白衣渡江,兵不血刃取荊州。', en: 'Rush. In white robes he crossed the river and took Jingzhou without a fight.' },
  },
  'gan-ning': {
    dynasty: 'wu',
    doctrine: 'separatist',
    rarity: 'epic',
    attack: 4,
    health: 5,
    keywords: ['charge'],
    battlecry: { ops: [{ op: 'aoeDamage', amount: 1 }] },
    text: { zh: '衝鋒。戰吼:對所有敵方武將造成1點傷害。百騎劫魏營,錦帆賊之名震天下。', en: 'Charge. Battlecry: Deal 1 damage to all enemy generals. A hundred riders raided the Wei camp.' },
  },
  'dong-zhuo': {
    dynasty: 'qun',
    doctrine: 'separatist',
    rarity: 'epic',
    cost: 7,
    attack: 7,
    health: 8,
    battlecry: { ops: [{ op: 'damage', amount: 2, target: 'friendlyHero' }] },
    text: { zh: '戰吼:對我方主公造成2點傷害。暴虐無道,天下共怨。', en: 'Battlecry: Deal 2 damage to your own hero. His tyranny bled friend and foe alike.' },
  },
  'yuan-shao': {
    dynasty: 'qun',
    attack: 4,
    health: 6,
    battlecry: {
      ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }],
      condition: { ifDynastyCount: { dynasty: 'qun', atLeast: 2 } },
    },
    text: { zh: '戰吼:若你控制至少2名群勢力武將,友方群勢力武將+1/+1。四世三公,門生故吏遍天下。', en: 'Battlecry: If you control 2+ Qun generals, give your Qun generals +1/+1.' },
  },
  'meng-huo': {
    dynasty: 'qun',
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 7,
    attack: 5,
    health: 6,
    deathrattle: { ops: [{ op: 'summon', defId: 'zhu-rong', count: 1 }] },
    text: { zh: '遺計:召喚祝融夫人。七擒七縱終不悔,蠻王身後有蠻后。', en: 'Deathrattle: Summon Lady Zhurong. Captured seven times — avenged once.' },
  },
  'hist-li-cunxiao': {
    keywords: ['duel'],
    text: { zh: '單挑。王不過項,將不過李。', en: 'Duel. No king surpassed Xiang Yu; no general surpassed Li Cunxiao.' },
  },
  'hist-an-lushan': {
    attack: 6,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。漁陽鼙鼓動地來。', en: 'Charge. The war drums of Yuyang shook the earth.' },
  },
  'hist-goujian': {
    attack: 5,
    health: 6,
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'self' }] },
    text: { zh: '戰吼:臥薪嘗膽,自身+2/+2。三千越甲可吞吳。', en: 'Battlecry: Sleep on firewood, taste the gall — gain +2/+2. Three thousand Yue armors can swallow Wu.' },
  },
  'sun-jian': {
    dynasty: 'wu',
    doctrine: 'separatist',
    cost: 6,
    attack: 6,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。江東猛虎,洛陽井中獨得傳國璽。', en: 'Charge. The Tiger of Jiangdong drew the Imperial Seal from a Luoyang well.' },
  },
  'gongsun-zan': {
    dynasty: 'qun',
    doctrine: 'separatist',
    rarity: 'rare',
    attack: 6,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。白馬義從,義之所至,生死相隨。', en: 'Rush. The White Horse Volunteers follow him past death.' },
  },
  'hist-chen-sheng': {
    attack: 4,
    health: 6,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方楚漢勢力武將+1/+1。王侯將相,寧有種乎!', en: 'Battlecry: Give your Chu-Han generals +1/+1. Are kings and ministers born to their station?' },
  },
  'hist-huang-chao': {
    attack: 6,
    health: 6,
    battlecry: { ops: [{ op: 'aoeDamage', amount: 1 }] },
    text: { zh: '戰吼:對所有敵方武將造成1點傷害。待到秋來九月八,滿城盡帶黃金甲。', en: 'Battlecry: Deal 1 damage to all enemy generals. When autumn comes, the whole city wears golden armor.' },
  },
  'hist-chen-youliang': {
    attack: 7,
    health: 5,
    keywords: ['duel'],
    text: { zh: '單挑。樓船蔽江,六十萬眾決死鄱陽湖。', en: 'Duel. His tower ships blotted out the river at Lake Poyang.' },
  },
  'hist-zhang-shicheng': {
    attack: 4,
    health: 7,
    keywords: ['guard'],
    text: { zh: '守護。十八條扁擔起事,據吳自守十四年。', en: 'Guard. Eighteen salt-carriers rose with him; he held Wu for fourteen years.' },
  },

  // ---- 割据扩充:历代割据军阀、称王称帝者、起义领袖、藩镇与海上势力 ----
  // 生成层只有 56 张割据卡,「割据」当职业撑不起构筑。以下将花名册中真正割地自守、
  // 举兵称制的人物从中立提入割据;数值一律按 总身材 = cost*2+1 减去关键词/效果计价。
  'yuan-shu': {
    doctrine: 'separatist',
    rarity: 'epic',
    cost: 5,
    attack: 5,
    health: 5,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方群勢力武將+1/+1。傳國玉璽在此,吾為仲家天子!', en: 'Battlecry: Give your Qun generals +1/+1. The Imperial Seal is mine — I am the Zhongjia Emperor.' },
  },
  'liu-biao': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 4,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。單騎入宜城,坐保江漢十八年,帶甲十餘萬。', en: 'Guard. He rode alone into Yicheng and held the Han valley for eighteen years.' },
  },
  'liu-zhang': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 4,
    attack: 2,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。「父子在州二十餘年,無恩德以加百姓」——遂開城以免兵禍。', en: 'Guard. Twenty years in Yi Province, and in the end he opened the gates to spare his people.' },
  },
  'zhang-lu': {
    doctrine: 'separatist',
    rarity: 'epic',
    cost: 5,
    attack: 4,
    health: 6,
    battlecry: { ops: [{ op: 'heal', amount: 4, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公4點生命。五斗米道據漢中三十年,義舍置米肉,行路者量腹取足。', en: 'Battlecry: Restore 4 Health to your hero. His Five Pecks of Rice ruled Hanzhong for thirty years, free rice at every waystation.' },
  },
  'han-sui': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 6,
    attack: 6,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。縱橫西涼三十餘年,關中十部,唯此老不死。', en: 'Rush. Thirty years astride the Liang frontier — of the ten warlords, only he endured.' },
  },
  'ma-teng': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 6,
    attack: 5,
    health: 7,
    keywords: ['guard'],
    text: { zh: '守護。身長八尺,西涼豪右歸心;衣帶詔既出,老將赴死不悔。', en: 'Guard. Eight feet tall, lord of the western marches — and he answered the girdle edict knowing the price.' },
  },
  'shi-xie': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。交趾四十年,出入鳴鐘磬,胡人夾轂焚香者常數十。', en: 'Battlecry: Draw a card. Forty years lord of Jiaozhi; incense-bearers ran beside his carriage.' },
  },
  'gongsun-du': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 5,
    health: 5,
    keywords: ['rush'],
    text: { zh: '突襲。自立為遼東侯、平州牧,東伐高句麗,西擊烏丸。', en: 'Rush. He named himself Marquis of Liaodong and struck east and west as he pleased.' },
  },
  'gongsun-kang': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'damage', amount: 3, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成3點傷害。伏兵斬二袁之首,函送許都——遼東自此無患。', en: 'Battlecry: Deal 3 damage to an enemy general. He boxed the Yuan brothers’ heads and sent them south.' },
  },
  'zhang-xiu': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 6,
    attack: 6,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。宛城一夜反戈,長子、愛將、駿馬,盡折於此。', en: 'Charge. One night at Wancheng cost Cao Cao his eldest son, his champion, and his horse.' },
  },
  'zhang-yan': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 4,
    health: 6,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方群勢力武將+1/+1。黑山百萬之眾,山谷為家,飛燕號令一出而山鳴。', en: 'Battlecry: Give your Qun generals +1/+1. A million of the Black Mountain answered the Flying Swallow.' },
  },
  'zhang-bao-yt': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'aoeDamage', amount: 1 }] },
    text: { zh: '戰吼:對所有敵方武將造成1點傷害。地公將軍作法,風雷驟起,飛沙走石。', en: 'Battlecry: Deal 1 damage to all enemy generals. The General of Earth called down wind and grit.' },
  },
  'zhang-liang-yt': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 4,
    keywords: ['guard'],
    text: { zh: '守護。人公將軍死守廣宗,城破之日,無一人降。', en: 'Guard. The General of Men held Guangzong to the last; not one man surrendered.' },
  },
  'tao-qian': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 5,
    deathrattle: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '遺計:抽一張牌。三讓徐州,臨終但曰:「非劉備不能安此州也。」', en: 'Deathrattle: Draw a card. Thrice he offered Xu Province away; at the end he named Liu Bei its only hope.' },
  },
  'hist-wu-guang': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 5,
    health: 4,
    keywords: ['charge'],
    text: { zh: '衝鋒。「今亡亦死,舉大計亦死」——大澤鄉中,斬木為兵。', en: 'Charge. Death for desertion, death for revolt — at Dazexiang they cut staves for spears.' },
  },
  'hist-wei-bao': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 4,
    keywords: ['rush'],
    text: { zh: '突襲。復魏地二十餘城而王之,叛楚叛漢,只認河東。', en: 'Rush. He retook twenty cities of Wei and crowned himself — loyal only to Hedong.' },
  },
  'hist-tian-rong': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 5,
    health: 5,
    keywords: ['guard'],
    text: { zh: '守護。並三齊之地拒霸王,楚兵頓於城下者累月。', en: 'Guard. He fused the three Qi lands into one and stalled the Hegemon for months.' },
  },
  'hist-shi-siming': {
    doctrine: 'separatist',
    rarity: 'epic',
    cost: 6,
    attack: 6,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。范陽再叛,自稱大燕皇帝,鐵騎復陷東都。', en: 'Charge. He revolted anew, styled himself Emperor of Great Yan, and took Luoyang a second time.' },
  },
  'hist-tian-chengsi': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 6,
    attack: 5,
    health: 7,
    keywords: ['guard'],
    text: { zh: '守護。魏博牙兵,父死子繼;河朔三鎮,不奉朝命者百年。', en: 'Guard. The Weibo guards passed from father to son; for a century the three garrisons ignored the court.' },
  },
  'hist-wang-xianzhi-tang': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 5,
    health: 5,
    keywords: ['rush'],
    text: { zh: '突襲。自號天補平均大將軍,長垣一呼,流民雲集。', en: 'Rush. He called himself the General Who Levels All Under Heaven, and the starving came.' },
  },
  'hist-du-fuwei': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 6,
    attack: 6,
    health: 6,
    keywords: ['rush'],
    text: { zh: '突襲。江淮舉義,每戰選死士為前鋒,退者立斬;十六歲已為群盜之長。', en: 'Rush. He led the Jianghuai rising at sixteen; his forlorn hope never retreated twice.' },
  },
  'hist-wang-shichong': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。廢皇泰主而自立為鄭,據東都,巧言足以動眾。', en: 'Battlecry: Draw a card. He deposed a boy emperor, took Luoyang, and talked an army into believing him.' },
  },
  'hist-liu-heita': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 6,
    attack: 7,
    health: 5,
    keywords: ['duel'],
    text: { zh: '單挑。半年盡復竇建德故地,自稱漢東王——河北之人,終不肯忘。', en: 'Duel. In half a year he won back all of Dou Jiande’s land; Hebei never forgot him.' },
  },
  'hist-wang-jian-shu': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 6,
    attack: 5,
    health: 7,
    battlecry: { ops: [{ op: 'gainArmor', amount: 3 }] },
    text: { zh: '戰吼:我方主公獲得3點護甲。閉劍門而王蜀,中原鼎沸,獨此一隅粟帛豐盈。', en: 'Battlecry: Gain 3 Armor. He shut the Sword Gate and ruled Shu while the plains burned.' },
  },
  'hist-meng-zhixiang': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 4,
    health: 6,
    battlecry: { ops: [{ op: 'heal', amount: 4, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公4點生命。據兩川而稱帝,天府之國,足以養一世偏安。', en: 'Battlecry: Restore 4 Health to your hero. He crowned himself in Shu, where the land alone can feed a dynasty.' },
  },
  'hist-ma-yin': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。鑄鉛鐵為錢,通商中原,湖南由是富庶。', en: 'Battlecry: Draw a card. He minted lead and iron coin, and trade made Hunan rich.' },
  },
  'hist-zhang-xianzhong': {
    doctrine: 'separatist',
    rarity: 'epic',
    cost: 6,
    attack: 6,
    health: 5,
    battlecry: { ops: [{ op: 'aoeDamage', amount: 1 }] },
    text: { zh: '戰吼:對所有敵方武將造成1點傷害。黃虎入蜀,建號大西,所過城郭為之一空。', en: 'Battlecry: Deal 1 damage to all enemy generals. The Yellow Tiger entered Shu and left it hollow.' },
  },
  'hist-liu-futong': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 6,
    attack: 5,
    health: 6,
    battlecry: { ops: [{ op: 'damage', amount: 3, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成3點傷害。「石人一隻眼,挑動黃河天下反。」紅巾三路北伐。', en: 'Battlecry: Deal 3 damage to an enemy general. One-eyed stone man — and the Yellow River rose in revolt.' },
  },
  'hist-fang-guozhen': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 5,
    health: 5,
    keywords: ['rush'],
    text: { zh: '突襲。首舉義旗於海上,舟師出沒,漕運為之斷絕。', en: 'Rush. First to raise the banner — at sea, where his fleets cut the grain lanes.' },
  },
  'hist-du-wenxiu': {
    doctrine: 'separatist',
    rarity: 'rare',
    cost: 5,
    attack: 4,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。據大理十八年,號總統兵馬大元帥,漢回並用,滇西自守。', en: 'Guard. Eighteen years he held Dali, Han and Hui alike under one banner.' },
  },

  // ================= 隐逸 reclusion =================
  // 隐逸卡池极薄(生成层仅17张),以下将方士/神医/隐士从中立改判入隐逸。
  'hist-laozi': {
    rarity: 'legendary',
    cost: 5,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 4, target: 'friendlyHero' }, { op: 'draw', count: 1 }] },
    text: { zh: '戰吼:恢復我方主公4點生命,抽一張牌。上善若水,道法自然。', en: 'Battlecry: Restore 4 Health to your hero and draw a card. The highest good is like water.' },
  },
  'hist-zhuangzi': {
    rarity: 'epic',
    cost: 5,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 2 }] },
    text: { zh: '戰吼:抽兩張牌。不知周之夢為蝴蝶與,蝴蝶之夢為周與?', en: 'Battlecry: Draw 2 cards. Was it Zhuang dreaming the butterfly, or the butterfly dreaming Zhuang?' },
  },
  'zuo-ci': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    attack: 3,
    health: 2,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。擲杯戲曹,幻化無窮。', en: 'Battlecry: Draw a card. He mocked Cao Cao with conjured cups.' },
  },
  'yu-ji': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    attack: 2,
    health: 4,
    deathrattle: { ops: [{ op: 'damage', amount: 3, target: 'randomEnemyGeneral' }] },
    text: { zh: '遺計:對一名隨機敵方武將造成3點傷害。怨魂不散,索命江東。', en: 'Deathrattle: Deal 3 damage to a random enemy general. His vengeful ghost haunted Sun Ce to death.' },
  },
  'hua-tuo': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    attack: 2,
    health: 3,
    battlecry: { ops: [{ op: 'heal', amount: 4, target: 'chosenAny' }] },
    text: { zh: '戰吼:恢復一個角色4點生命。刮骨療毒,妙手回春。', en: 'Battlecry: Restore 4 Health to a character. He scraped poison from the bone.' },
  },
  'sima-hui': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    attack: 2,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。水鏡先生,坐薦臥龍鳳雛。', en: 'Battlecry: Draw a card. Master Water-Mirror pointed the way to the Sleeping Dragon.' },
  },
  'hist-tao-yuanming': {
    attack: 3,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。采菊東籬下,悠然見南山。', en: 'Battlecry: Restore 3 Health to your hero. Picking chrysanthemums by the eastern fence.' },
  },
  'ji-kang': {
    dynasty: 'qun',
    deathrattle: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '遺計:抽一張牌。《廣陵散》於今絕矣。', en: 'Deathrattle: Draw a card. Guangling San dies with him.' },
  },
  'xu-shu': {
    dynasty: 'qun',
    keywords: ['guard'],
    text: { zh: '守護。身在曹營心在漢,一言不發亦護主。', en: 'Guard. In Cao’s camp, his heart stayed with Han — silent, but steadfast.' },
  },
  'hist-li-bai': {
    attack: 4,
    health: 4,
    keywords: ['windfury'],
    text: { zh: '連擊。十步殺一人,千里不留行。', en: 'Windfury. A kill every ten paces, no trace for a thousand li.' },
  },
  'hist-guiguzi': {
    doctrine: 'reclusion',
    cost: 5,
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'chosenAny' }] },
    text: { zh: '戰吼:使一名武將+2/+2。鬼谷授徒,出將入相。', en: 'Battlecry: Give a general +2/+2. His students became generals and chancellors.' },
  },
  // 医者双璧:治疗战吼撑不起场面,身材按满曲线给。
  // 张仲景须守住 2 费位 —— 隐逸预组的唯一早期随从,挪到 3 费整套曲线就塌(sim-balance 实测 -14%)。
  'hist-bian-que': {
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'heal', amount: 4, target: 'chosenAny' }] },
    text: { zh: '戰吼:恢復一個角色4點生命。望聞問切,起死回生。', en: 'Battlecry: Restore 4 Health to a character. He read life and death at a glance.' },
  },
  'zhang-zhongjing': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 2,
    attack: 3,
    health: 2,
    battlecry: { ops: [{ op: 'heal', amount: 2, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公2點生命。傷寒雜病,一論而癒。', en: 'Battlecry: Restore 2 Health to your hero. The Treatise on Cold Damage healed a plagued age.' },
  },
  'hist-wang-xizhi': {
    attack: 3,
    health: 5,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。永和九年,曲水流觴,天下第一行書。', en: 'Battlecry: Draw a card. At the Orchid Pavilion — the finest running script under heaven.' },
  },
  'hist-wang-wei': {
    attack: 3,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。行到水窮處,坐看雲起時。', en: 'Battlecry: Restore 3 Health to your hero. Where the stream ends, sit and watch the clouds rise.' },
  },
  'hist-tao-hongjing': {
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'heal', amount: 2, target: 'friendlyHero' }, { op: 'draw', count: 1 }] },
    text: { zh: '戰吼:恢復我方主公2點生命,抽一張牌。山中宰相,嶺上白雲堪寄國事。', en: 'Battlecry: Restore 2 Health to your hero and draw a card. The Chancellor in the Mountains answered the court from among white clouds.' },
  },
  'hist-yan-guang': {
    attack: 4,
    health: 5,
    deathrattle: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '遺計:抽一張牌。富春江上一竿風月,足加帝腹傲王侯。', en: 'Deathrattle: Draw a card. He fished the Fuchun River and rested his feet on an emperor’s belly.' },
  },
  'hist-li-shizhen': {
    attack: 3,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'chosenAny' }] },
    text: { zh: '戰吼:恢復一個角色3點生命。遍嘗百草,綱目乃成。', en: 'Battlecry: Restore 3 Health to a character. He tasted a hundred herbs to write the Compendium.' },
  },

  // ---- 隐逸扩充:隐士、道家方术、医者、僧道、山水文人与书画家 ----
  // 生成层只有 17 张隐逸卡,连一套构筑都撑不满。以下按「辞官归隐 / 道医方术 / 卜筮天文 /
  // 布衣书画」四类从花名册提人;身材守 cost*2+1,治疗与护甲在贪心 AI 里近乎零收益,按满曲线给。

  // 三国:荆襄隐逸圈、方术医者与竹林诸贤
  'pang-degong': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 3,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'chosenAny' }] },
    text: { zh: '戰吼:使一名武將+1/+1。鹿門採藥不返,識臥龍鳳雛於草廬未起時。', en: 'Battlecry: Give a general +1/+1. He named the Sleeping Dragon and the Fledgling Phoenix, then went to the hills for herbs and never came back.' },
  },
  'huang-chengyan': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 2,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。沔南名士,以醜女妻臥龍;八陣圖中,獨他識得生門。', en: 'Battlecry: Draw a card. He married his plain daughter to Zhuge Liang — and alone knew the way out of the Eight Formations.' },
  },
  'cui-zhouping': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    text: { zh: '談笑山林,不問興廢。「治亂有數,君何必強求?」', en: 'Order and chaos each have their season — why force it, sir?' },
  },
  'shi-tao': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 4,
    text: { zh: '荊襄遊學四友之一,務於精純,終不求聞達。', en: 'One of the four who studied together in Jingxiang — precise, thorough, and content to be unknown.' },
  },
  'meng-jian': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 4,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。思歸故里,樂在鄉土,不慕京華。', en: 'Battlecry: Restore 3 Health to your hero. He longed for his home village and never envied the capital.' },
  },
  'guan-lu': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 3,
    deathrattle: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '遺計:抽一張牌。自言額無生骨、眼無守精,四十八乃終——果如其言。', en: 'Deathrattle: Draw a card. He read his own bones and gave himself forty-eight years. He was right.' },
  },
  'zhou-xuan': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 2,
    attack: 2,
    health: 2,
    deathrattle: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '遺計:抽一張牌。占夢無不中——夢中之事,醒後方驗。', en: 'Deathrattle: Draw a card. His readings of dreams never failed; they were only proved after waking.' },
  },
  'fan-a': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 2,
    attack: 2,
    health: 3,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'chosenAny' }] },
    text: { zh: '戰吼:恢復一個角色3點生命。針入五六寸,漆葉青黏散,壽百餘歲。', en: 'Battlecry: Restore 3 Health to a character. His needles went five inches deep; he lived past a hundred.' },
  },
  'wu-pu': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 2,
    attack: 2,
    health: 2,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'chosenAny' }] },
    text: { zh: '戰吼:使一名武將+1/+1。五禽之戲:身體輕便,穀氣得消,血脈流通。', en: 'Battlecry: Give a general +1/+1. The Five Animal Frolics: the body grows light, the blood runs free.' },
  },
  'ruan-ji': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 3,
    battlecry: { ops: [{ op: 'discardRandom', count: 1 }] },
    text: { zh: '戰吼:對手隨機棄一張牌。大醉六十日,求婚的文書終究無處落筆。', en: 'Battlecry: Your opponent discards a random card. Sixty days drunk — the marriage proposal never found a sober moment.' },
  },
  'xiang-xiu': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 3,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。注《莊子》發明奇趣,讀之者超然心悟。', en: 'Battlecry: Draw a card. His commentary on Zhuangzi opened doors readers had not known were shut.' },
  },
  'liu-ling': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 4,
    health: 3,
    text: { zh: '荷鍤而行,「死便埋我」;幕天席地,縱意所如。', en: 'He travelled with a spade: bury me where I drop. Sky for a tent, earth for a mat.' },
  },
  'ruan-xian': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 2,
    attack: 2,
    health: 3,
    text: { zh: '妙解音律,一曲琵琶傳千載;竹林之下,不減叔夜。', en: 'A master of pitch; the lute he shaped still bears his name.' },
  },
  'shan-tao': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。《山公啟事》一出,所舉必當,朝野無異議。', en: 'Battlecry: Draw a card. When Shan Tao named a man for office, no one at court disagreed.' },
  },
  'wang-rong': {
    dynasty: 'qun',
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'gainArmor', amount: 3 }] },
    text: { zh: '戰吼:我方主公獲得3點護甲。道邊苦李無人摘——守財亦是守心。', en: 'Battlecry: Gain 3 Armor. Bitter plums by the road go unpicked; a miser guards more than coin.' },
  },

  // 先秦:道家、稷下与市井隐者
  'hist-liezi': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。御風而行,泠然善也,旬有五日而後反。', en: 'Battlecry: Draw a card. He rode the wind, cool and easy, and came back on the fifteenth day.' },
  },
  'hist-yang-zhu': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 3,
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'self' }] },
    text: { zh: '戰吼:自身+2/+2。拔一毛而利天下,不為也——全性保真,不以物累形。', en: 'Battlecry: Gain +2/+2. Not one hair, though it save the world — keep your nature whole.' },
  },
  'hist-tian-pian': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 3,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。稷下「天口駢」,貴齊而不仕,終身不為人臣。', en: 'Battlecry: Draw a card. The Mouth of Heaven talked at the Jixia academy and never took a post.' },
  },
  'hist-huan-yuan': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 3,
    deathrattle: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '遺計:抽一張牌。著上下篇,言黃老道德之術,楚人謂之環子。', en: 'Deathrattle: Draw a card. Two scrolls on the Way and its Power — Chu called him simply Master Huan.' },
  },
  'hist-duangan-mu': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 4,
    keywords: ['guard'],
    text: { zh: '守護。踰垣而避,魏文侯過其閭必式;秦師聞之,不加兵於魏。', en: 'Guard. He climbed the wall to avoid office; the marquis bowed at his gate, and Qin declined to march.' },
  },
  'hist-yi-he': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 4, target: 'chosenAny' }] },
    text: { zh: '戰吼:恢復一個角色4點生命。「疾不可為也」——良醫先論其心,後論其身。', en: 'Battlecry: Restore 4 Health to a character. This illness cannot be cured — a great physician reads the heart first.' },
  },
  'hist-mao-gong': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。藏於博徒之中,信陵君屏左右而從之游。', en: 'Battlecry: Draw a card. He hid among gamblers; the Lord of Xinling dismissed his retinue to walk with him.' },
  },
  'hist-xue-gong': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方戰國勢力武將+1/+1。藏於賣漿家,一言而動公子之心。', en: 'Battlecry: Give your Warring States generals +1/+1. He hid in a wine-seller’s shop, and one sentence moved a prince.' },
  },
  'hist-huangshigong': {
    doctrine: 'reclusion',
    rarity: 'epic',
    cost: 5,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'chosenAny' }] },
    text: { zh: '戰吼:使一名武將+2/+2。圯上三進履,「孺子可教」;一編書出,而漢業以興。', en: 'Battlecry: Give a general +2/+2. Three times he made the boy fetch his shoe — then handed him the book that founded Han.' },
  },

  // 两汉魏晋南北朝:炼丹、天文、书画与山水
  'hist-wang-chong': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 2,
    health: 5,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。閉門潛思,戶牖牆壁各置刀筆;《論衡》一書,專疾虛妄。', en: 'Battlecry: Draw a card. He shut his door, kept brushes at every window, and wrote a book against nonsense.' },
  },
  'hist-zhang-heng': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 5,
    battlecry: { ops: [{ op: 'damage', amount: 2, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成2點傷害。銅丸墜於龍口,隴西地動,而京師未覺。', en: 'Battlecry: Deal 2 damage to an enemy general. A bronze ball dropped from the dragon’s mouth; days later, word of the quake arrived.' },
  },
  'hist-ge-hong': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。抱朴子入羅浮山煉丹,不以榮名累其身。', en: 'Battlecry: Restore 3 Health to your hero. The Master Who Embraces Simplicity went to Luofu to make elixirs, and let fame go.' },
  },
  'hist-gu-kaizhi': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 3,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'chosenAny' }] },
    text: { zh: '戰吼:使一名武將+1/+1。「傳神寫照,正在阿堵中。」', en: 'Battlecry: Give a general +1/+1. The spirit of a portrait lives right there — in the eyes.' },
  },
  'hist-wang-xianzhi': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 3,
    keywords: ['windfury'],
    text: { zh: '連擊。一筆書連綿不絕,大令與右軍,並稱二王。', en: 'Windfury. One unbroken stroke across the page — father and son, the Two Wangs.' },
  },
  'hist-shan-jian': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。日夕倒載歸,酩酊無所知——高陽池上一狂翁。', en: 'Battlecry: Restore 3 Health to your hero. Carried home backwards at dusk, blind drunk and perfectly happy.' },
  },
  'hist-xie-lingyun': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。「池塘生春草」;著木屐登山,天下才共一石。', en: 'Battlecry: Draw a card. Spring grass by the pond — he climbed mountains in cleated clogs and claimed most of the world’s talent.' },
  },
  'hist-kou-qianzhi': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 5,
    attack: 4,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。嵩岳受籙,清整道教;「太平真君」之號,自此而始。', en: 'Guard. He received the register on Mount Song, cleansed the Daoist rolls, and gave an emperor his reign-name.' },
  },
  'hist-xiao-ziyun': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 4,
    text: { zh: '飛白妙絕,百濟使者傾囊求書,不遠萬里而來。', en: 'His flying-white script was so fine that envoys from Baekje crossed the sea and emptied their purses for it.' },
  },

  // 唐:诗僧、道隐与狂草
  'hist-meng-haoran': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 4,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。「春眠不覺曉」;鹿門一臥,終身不仕。', en: 'Battlecry: Restore 3 Health to your hero. Asleep in spring, unaware of dawn — he lay down at Lumen and never rose for office.' },
  },
  'hist-he-zhizhang': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。四明狂客解金龜換酒;晚乞為道士,還鄉鏡湖。', en: 'Battlecry: Draw a card. The Madman of Siming traded his golden badge for wine, then asked to go home as a Daoist.' },
  },
  'hist-zhang-xu': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 2,
    keywords: ['windfury'],
    text: { zh: '連擊。醉後呼叫狂走,以髮濡墨——揮毫落紙如雲煙。', en: 'Windfury. Drunk, he ran shouting and dipped his hair for a brush; the ink came down like smoke.' },
  },
  'hist-xuanzang': {
    doctrine: 'reclusion',
    rarity: 'epic',
    cost: 5,
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }, { op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:抽一張牌,恢復我方主公3點生命。孤征十七年,負經六百五十七部而還。', en: 'Battlecry: Draw a card and restore 3 Health to your hero. Seventeen years alone on the road, and 657 scriptures carried home.' },
  },
  'hist-jianzhen': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 5,
    keywords: ['guard'],
    text: { zh: '守護。六次東渡,兩目失明而志不移;山川異域,風月同天。', en: 'Guard. Six crossings, both eyes lost, the vow unchanged: different lands, one sky.' },
  },
  'hist-li-bi': {
    doctrine: 'reclusion',
    rarity: 'epic',
    cost: 5,
    attack: 4,
    health: 4,
    battlecry: {
      ops: [
        { op: 'draw', count: 1 },
        { op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' },
      ],
    },
    text: { zh: '戰吼:抽一張牌,友方唐勢力武將+1/+1。功成即入衡山——山人宰相,四朝而不居其位。', en: 'Battlecry: Draw a card and give your Tang generals +1/+1. Each time the crisis passed, he went back to the mountain.' },
  },
  'hist-wang-zhihuan': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 4,
    keywords: ['rush'],
    text: { zh: '突襲。「欲窮千里目,更上一層樓。」拂衣去官,漫遊十五年。', en: 'Rush. To see a thousand li, climb one more storey. He shook out his sleeves, quit office, and wandered fifteen years.' },
  },
  'hist-yuan-jie': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 5,
    keywords: ['guard'],
    text: { zh: '守護。自號漫叟、浪士,結廬山谷之間;賊至,亦能全十五城。', en: 'Guard. He called himself the Idle Old Man — and still held fifteen cities when the rebels came.' },
  },
  'hist-wen-tingyun': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 2,
    attack: 3,
    health: 2,
    text: { zh: '八叉手而八韻成,花間之祖;屢舉不第,終老江湖。', en: 'Eight crossings of his hands, eight rhymes done. He never passed the exams, and never stopped writing.' },
  },

  // 宋元:布衣词人与山水画家
  'hist-mi-fu': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'gainArmor', amount: 3 }] },
    text: { zh: '戰吼:我方主公獲得3點護甲。整衣拜石,呼之為兄——米顛之名,世人笑而慕之。', en: 'Battlecry: Gain 3 Armor. He straightened his robe and bowed to a rock, calling it elder brother.' },
  },
  'hist-huang-tingjian': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 4,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'chosenAny' }] },
    text: { zh: '戰吼:使一名武將+1/+1。點鐵成金,奪胎換骨。', en: 'Battlecry: Give a general +1/+1. Touch iron and it turns to gold; borrow the bones and change the frame.' },
  },
  'hist-jiang-kui': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 3,
    battlecry: { ops: [{ op: 'heal', amount: 2, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公2點生命。白石道人自度曲,一生布衣,寄食江湖。', en: 'Battlecry: Restore 2 Health to your hero. The White Stone Daoist wrote his own tunes and lived his whole life a commoner.' },
  },
  'hist-zhong-fang': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 2,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。終南結廬三十年,真宗屢召,皆以母老辭。', en: 'Guard. Thirty years in a hut on Zhongnan; each imperial summons met the same reply — my mother is old.' },
  },
  'hist-wen-tong': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 4,
    health: 3,
    text: { zh: '畫竹必先得成竹於胸中;執筆熟視,乃見其所欲畫者。', en: 'Before painting bamboo, have the whole bamboo in your chest; hold the brush, look long, and it appears.' },
  },
  'hist-ma-yuan-song': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 4,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。人稱「馬一角」——殘山剩水裏,留得半壁江南。', en: 'Battlecry: Restore 3 Health to your hero. One-Corner Ma: half a mountain, half a river, and all of the south.' },
  },
  'hist-liu-yong-song': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 3,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。「忍把浮名,換了淺斟低唱。」奉旨填詞柳三變。', en: 'Battlecry: Draw a card. Trade a hollow name for a cup and a quiet song — by imperial order, a lyricist.' },
  },
  'hist-wu-wenying': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 3,
    deathrattle: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '遺計:抽一張牌。夢窗詞如七寶樓臺,拆碎下來,不成片段。', en: 'Deathrattle: Draw a card. His lyrics are a jewelled tower — take it apart and nothing fits.' },
  },
  'hist-su-shunqin': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。削籍為民,買地築滄浪亭:「滄浪之水清兮」。', en: 'Battlecry: Restore 3 Health to your hero. Stripped of rank, he bought a plot and built the Canglang Pavilion.' },
  },
  'hist-huang-gongwang': {
    doctrine: 'reclusion',
    rarity: 'epic',
    cost: 4,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'buffStats', attack: 2, health: 2, target: 'chosenAny' }] },
    text: { zh: '戰吼:使一名武將+2/+2。入全真為道士,富春江上三年,成一卷《山居圖》。', en: 'Battlecry: Give a general +2/+2. He took Daoist orders and spent three years on one scroll of the Fuchun hills.' },
  },
  'hist-ni-zan': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 4,
    keywords: ['guard'],
    text: { zh: '守護。散盡家財,扁舟往來太湖二十年;逸筆草草,不求形似。', en: 'Guard. He gave away his fortune and drifted Lake Tai for twenty years, painting loosely, chasing no likeness.' },
  },
  'hist-wu-zhen': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 2,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。梅花道人賣卜錢塘,不與權貴通一刺。', en: 'Battlecry: Draw a card. The Plum Blossom Daoist told fortunes in Qiantang and never sent a card to a lord.' },
  },
  'hist-wang-meng-yuan': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 4,
    deathrattle: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '遺計:抽一張牌。黃鶴山樵隱居三十年,解索一皴,寫盡林泉深秀。', en: 'Deathrattle: Draw a card. The Woodcutter of Yellow Crane Mountain hid thirty years and painted every fold of the forest.' },
  },
  'hist-ma-zhiyuan': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 3,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。「夕陽西下,斷腸人在天涯。」東籬本是風月主。', en: 'Battlecry: Draw a card. The sun sets west; the heartbroken man is at the sky’s edge.' },
  },
  'hist-bai-pu': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 4,
    text: { zh: '終身不仕,以詞曲自遣;故國之痛,盡寄梧桐雨聲。', en: 'He never took office. What he could not say about a fallen dynasty, he put into rain on the wutong leaves.' },
  },
  'hist-wang-shifu': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方元勢力武將+1/+1。「願天下有情的都成了眷屬。」', en: 'Battlecry: Give your Yuan generals +1/+1. May all the lovers in the world be joined.' },
  },

  // 明清:吴门书画、讲学布衣与著书隐者
  'hist-tang-yin': {
    doctrine: 'reclusion',
    rarity: 'epic',
    cost: 4,
    attack: 4,
    health: 5,
    battlecry: { ops: [{ op: 'heal', amount: 3, target: 'friendlyHero' }] },
    text: { zh: '戰吼:恢復我方主公3點生命。桃花塢裏桃花庵,酒醒只在花前坐——不願鞠躬車馬前。', en: 'Battlecry: Restore 3 Health to your hero. A hut among peach blossoms; he would rather sit with the flowers than bow to a carriage.' },
  },
  'hist-wen-zhengming': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。九試不第,歸而弄翰;停雲館中,八十九歲猶作書。', en: 'Battlecry: Draw a card. Nine failed exams, then home to the brush — at eighty-nine he was still writing.' },
  },
  'hist-shen-zhou': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 2,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。有司欲薦之,卜《易》得遯之九五,遂終身不仕。', en: 'Guard. Offered a recommendation, he consulted the Yijing, drew Retreat, and never served.' },
  },
  'hist-qiu-ying': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 4,
    text: { zh: '漆工出身,十年成一卷;仕女樓閣,設色如新。', en: 'A lacquerer’s apprentice who spent ten years on a single scroll — the colours still look wet.' },
  },
  'hist-zhu-zhishan': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 3,
    health: 3,
    battlecry: { ops: [{ op: 'discardRandom', count: 1 }] },
    text: { zh: '戰吼:對手隨機棄一張牌。狂草一揮而就,墨濺鄰座之卷,索書者猶爭之。', en: 'Battlecry: Your opponent discards a random card. His wild cursive splashed the next man’s scroll — and they still fought over it.' },
  },
  'hist-xu-zhenqing': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 4,
    deathrattle: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '遺計:抽一張牌。吳中詩冠,晚而好道,三十有三而遽歸。', en: 'Deathrattle: Draw a card. First poet of Wu; he turned to the Way late, and left at thirty-three.' },
  },
  'hist-chen-xianzhang': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'buffStats', attack: 1, health: 1, target: 'friendlyDynastyGenerals' }] },
    text: { zh: '戰吼:友方明勢力武將+1/+1。築陽春臺靜坐,學貴自得;白沙門下多真儒。', en: 'Battlecry: Give your Ming generals +1/+1. He built a terrace, sat still, and taught that learning must be found for oneself.' },
  },
  'hist-wang-ji': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。龍溪講學四十年,四方從者不絕於途。', en: 'Battlecry: Draw a card. Forty years lecturing at Longxi, with students arriving from every direction.' },
  },
  'hist-wu-jingzi': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 4,
    health: 4,
    battlecry: { ops: [{ op: 'damage', amount: 2, target: 'chosenEnemyGeneral' }] },
    text: { zh: '戰吼:對一名敵方武將造成2點傷害。一支筆刺穿儒林——「功名富貴無憑據」。', en: 'Battlecry: Deal 2 damage to an enemy general. One brush ran the scholars through: rank and riches prove nothing.' },
  },
  'hist-yuan-mei': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 4,
    attack: 3,
    health: 4,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。三十三歲辭官,築隨園,不復出仕。', en: 'Battlecry: Draw a card. He resigned at thirty-three, built the Sui Garden, and never went back.' },
  },
  'hist-jiao-xun': {
    doctrine: 'reclusion',
    rarity: 'rare',
    cost: 3,
    attack: 2,
    health: 3,
    battlecry: { ops: [{ op: 'draw', count: 1 }] },
    text: { zh: '戰吼:抽一張牌。足不入城十餘年,雕菰樓上,成一部《易通釋》。', en: 'Battlecry: Draw a card. Ten years without entering the town, and one book on the Yijing to show for it.' },
  },

  // ================= 中立签名(简单关键词) =================
  'lu-bu': {
    dynasty: 'qun',
    rarity: 'legendary',
    cost: 8,
    attack: 10,
    health: 6,
    keywords: ['duel'],
    text: { zh: '單挑。人中呂布,馬中赤兔。', en: 'Duel. Among men, Lu Bu; among horses, Red Hare.' },
  },
  'dian-wei': {
    dynasty: 'wei',
    attack: 6,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。古之惡來,死守轅門。', en: 'Guard. The Evil Comes of old held the gate to his death.' },
  },
  'hua-xiong': {
    dynasty: 'qun',
    cost: 5,
    attack: 6,
    health: 4,
    keywords: ['duel'],
    text: { zh: '單挑。汜水關前連斬上將——直到那杯酒尚溫。', en: 'Duel. He felled champion after champion — until the wine was still warm.' },
  },
  'yan-liang': {
    dynasty: 'qun',
    attack: 6,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。河北名將,先聲奪人。', en: 'Charge. Hebei’s champion strikes first.' },
  },
  'wen-chou': {
    dynasty: 'qun',
    attack: 6,
    health: 5,
    keywords: ['rush'],
    text: { zh: '突襲。延津突騎,爭先赴敵。', en: 'Rush. The shock riders of Yanjin.' },
  },
  'zhou-tai': {
    dynasty: 'wu',
    attack: 5,
    health: 7,
    keywords: ['guard'],
    text: { zh: '守護。渾身刀痕,護主周全。', en: 'Guard. Every scar a debt repaid.' },
  },
  'huang-gai': {
    dynasty: 'wu',
    attack: 5,
    health: 6,
    keywords: ['charge'],
    text: { zh: '衝鋒。火船衝陣,苦肉建功。', en: 'Charge. Fire ships ram the line.' },
  },
  'ding-feng': {
    dynasty: 'wu',
    attack: 6,
    health: 5,
    keywords: ['rush'],
    text: { zh: '突襲。雪中奮短兵。', en: 'Rush. Short blades in the snow.' },
  },
  'wei-yan': {
    dynasty: 'shu',
    attack: 6,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。子午谷奇謀未售,先登陷陣有餘。', en: 'Charge. His Ziwu Valley gambit was refused — his vanguard never was.' },
  },
  'liao-hua': {
    dynasty: 'shu',
    keywords: ['rush'],
    text: { zh: '突襲。蜀中無大將,廖化作先鋒。', en: 'Rush. When Shu ran out of great generals, Liao Hua led the van.' },
  },
  'chen-dao': {
    dynasty: 'shu',
    attack: 5,
    health: 7,
    keywords: ['guard'],
    text: { zh: '守護。白毦精兵,護衛中軍。', en: 'Guard. The White Feather Guard shields the center.' },
  },
  'ma-dai': {
    dynasty: 'shu',
    cost: 5,
    attack: 5,
    health: 5,
    keywords: ['rush'],
    text: { zh: '突襲。陣前一刀,襲斬魏延。', en: 'Rush. One stroke from behind ended Wei Yan.' },
  },
  'wang-ping': {
    dynasty: 'shu',
    cost: 5,
    attack: 4,
    health: 6,
    keywords: ['guard'],
    text: { zh: '守護。無當飛軍,山地爭鋒;街亭之敗,獨全一軍。', en: 'Guard. At Jieting, only his troops came back whole.' },
  },
  'cheng-pu': {
    dynasty: 'wu',
    attack: 5,
    health: 7,
    keywords: ['guard'],
    text: { zh: '守護。三朝宿將;與周郎交,若飲醇醪。', en: 'Guard. A veteran of three lords — knowing Zhou Yu was like drinking mellow wine.' },
  },
  'le-jin': {
    dynasty: 'wei',
    cost: 5,
    attack: 5,
    health: 5,
    keywords: ['charge'],
    text: { zh: '衝鋒。每戰先登,驍果為先。', en: 'Charge. First over the wall in every assault.' },
  },
  'wen-yang': {
    dynasty: 'wei',
    doctrine: 'neutral',
    attack: 5,
    health: 5,
    keywords: ['windfury'],
    text: { zh: '連擊。單騎退雄兵,七進七出,追者莫敢近。', en: 'Windfury. Alone he turned back an army — seven times in, seven times out.' },
  },
}
