import type { CardDef } from '../../engine/types'

// 锦囊牌:非武将、手工设计。id 前缀 strat-,collectorNo 从 9001 起顺延。
// 含 chosen* 操作的锦囊在无合法目标时不可施放(引擎语义)。
export const STRATAGEMS: CardDef[] = [
  {
    id: 'strat-huo-ji',
    collectorNo: 9001,
    name: { zh: '火計', en: 'Fire Attack' },
    type: 'stratagem',
    doctrine: 'neutral',
    dynasty: 'qun',
    rarity: 'common',
    archetype: 'strategist',
    cost: 3,
    keywords: [],
    spell: { ops: [{ op: 'damage', amount: 4, target: 'chosenEnemyGeneral' }] },
    text: { zh: '對一名敵方武將造成4點傷害。以火佐攻者明。', en: 'Deal 4 damage to an enemy general.' },
  },
  {
    id: 'strat-lianhuan-ji',
    collectorNo: 9002,
    name: { zh: '連環計', en: 'Chain Stratagem' },
    type: 'stratagem',
    doctrine: 'fame',
    dynasty: 'qun',
    rarity: 'rare',
    archetype: 'strategist',
    cost: 4,
    keywords: [],
    spell: { ops: [{ op: 'aoeDamage', amount: 2 }] },
    text: { zh: '對所有敵方武將造成2點傷害。鐵索連舟,一燒俱盡。', en: 'Deal 2 damage to all enemy generals. Chained hulls burn together.' },
  },
  {
    id: 'strat-kurou-ji',
    collectorNo: 9003,
    name: { zh: '苦肉計', en: 'Self-Injury Ploy' },
    type: 'stratagem',
    doctrine: 'separatist',
    dynasty: 'wu',
    rarity: 'rare',
    archetype: 'strategist',
    cost: 2,
    keywords: [],
    spell: { ops: [{ op: 'damage', amount: 3, target: 'friendlyHero' }, { op: 'draw', count: 2 }] },
    text: { zh: '對我方主公造成3點傷害,抽兩張牌。周瑜打黃蓋,一個願打一個願挨。', en: 'Deal 3 damage to your hero, then draw 2 cards.' },
  },
  {
    id: 'strat-fanjian-ji',
    collectorNo: 9004,
    name: { zh: '反間計', en: 'Sowing Discord' },
    type: 'stratagem',
    doctrine: 'fame',
    dynasty: 'wu',
    rarity: 'rare',
    archetype: 'strategist',
    cost: 4,
    keywords: [],
    spell: {
      ops: [
        { op: 'damage', amount: 3, target: 'randomEnemyGeneral' },
        { op: 'damage', amount: 3, target: 'randomEnemyGeneral' },
      ],
    },
    text: { zh: '對隨機敵方武將造成3點傷害,兩次。蔣幹盜書,自折兩員水軍都督。', en: 'Deal 3 damage to a random enemy general, twice. Suspicion cuts deeper than swords.' },
  },
  {
    id: 'strat-kongcheng-ji',
    collectorNo: 9005,
    name: { zh: '空城計', en: 'Empty Fort' },
    type: 'stratagem',
    doctrine: 'reclusion',
    dynasty: 'shu',
    rarity: 'rare',
    archetype: 'strategist',
    cost: 2,
    keywords: [],
    spell: { ops: [{ op: 'heal', amount: 8, target: 'friendlyHero' }] },
    text: { zh: '恢復我方主公8點生命。大開城門,焚香操琴,追兵疑而自退。', en: 'Restore 8 Health to your hero. Open gates, burning incense, a lone qin — the pursuers turn back.' },
  },
  {
    id: 'strat-caochuan-jiejian',
    collectorNo: 9006,
    name: { zh: '草船借箭', en: 'Borrowing Arrows' },
    type: 'stratagem',
    doctrine: 'royal',
    dynasty: 'shu',
    rarity: 'common',
    archetype: 'strategist',
    cost: 3,
    keywords: [],
    spell: { ops: [{ op: 'draw', count: 2 }] },
    text: { zh: '抽兩張牌。霧鎖大江,一夜借得十萬箭。', en: 'Draw 2 cards. One foggy night, a hundred thousand arrows — borrowed.' },
  },
  {
    id: 'strat-jie-dongfeng',
    collectorNo: 9007,
    name: { zh: '借東風', en: 'Summon the East Wind' },
    type: 'stratagem',
    doctrine: 'reclusion',
    dynasty: 'shu',
    rarity: 'rare',
    archetype: 'strategist',
    cost: 2,
    keywords: [],
    spell: { ops: [{ op: 'grantKeyword', keyword: 'windfury', target: 'chosenAny' }] },
    text: { zh: '使一名武將獲得連擊。七星壇上作法,東風夜起。', en: 'Give a general Windfury. The east wind rises at the Seven Star Altar.' },
  },
  {
    id: 'strat-weiwei-jiuzhao',
    collectorNo: 9008,
    name: { zh: '圍魏救趙', en: 'Besiege Wei to Rescue Zhao' },
    type: 'stratagem',
    doctrine: 'separatist',
    dynasty: 'warring-states',
    rarity: 'common',
    archetype: 'strategist',
    cost: 3,
    keywords: [],
    spell: {
      ops: [
        { op: 'damage', amount: 3, target: 'enemyHero' },
        { op: 'heal', amount: 3, target: 'friendlyHero' },
      ],
    },
    text: { zh: '對敵方主公造成3點傷害,恢復我方主公3點生命。攻其必救。', en: 'Deal 3 damage to the enemy hero; restore 3 Health to yours. Strike what they must save.' },
  },
  {
    id: 'strat-andu-chencang',
    collectorNo: 9009,
    name: { zh: '暗度陳倉', en: 'Secret Passage to Chencang' },
    type: 'stratagem',
    doctrine: 'hegemonic',
    dynasty: 'chu-han',
    rarity: 'common',
    archetype: 'strategist',
    cost: 4,
    keywords: [],
    spell: { ops: [{ op: 'damage', amount: 4, target: 'enemyHero' }] },
    text: { zh: '對敵方主公造成4點傷害。明修棧道,奇兵已出陳倉。', en: 'Deal 4 damage to the enemy hero. Repair the plank road openly; strike from Chencang unseen.' },
  },
  {
    id: 'strat-beishui-yizhan',
    collectorNo: 9010,
    name: { zh: '背水一戰', en: 'Last Stand at the River' },
    type: 'stratagem',
    doctrine: 'hegemonic',
    dynasty: 'chu-han',
    rarity: 'rare',
    archetype: 'strategist',
    cost: 3,
    keywords: [],
    spell: {
      ops: [
        { op: 'buffStats', attack: 2, health: 2, target: 'chosenAny' },
        { op: 'grantKeyword', keyword: 'charge', target: 'chosenAny' },
      ],
    },
    text: { zh: '使一名武將+2/+2並獲得衝鋒。陷之死地而後生。', en: 'Give a general +2/+2 and Charge. Placed on deadly ground, soldiers fight to live.' },
  },
  {
    id: 'strat-pofu-chenzhou',
    collectorNo: 9011,
    name: { zh: '破釜沉舟', en: 'Burn the Boats' },
    type: 'stratagem',
    doctrine: 'hegemonic',
    dynasty: 'chu-han',
    rarity: 'epic',
    archetype: 'strategist',
    cost: 3,
    keywords: [],
    spell: {
      ops: [
        { op: 'buffStats', attack: 3, health: 2, target: 'chosenAny' },
        { op: 'damage', amount: 2, target: 'friendlyHero' },
      ],
    },
    text: { zh: '使一名武將+3/+2,對我方主公造成2點傷害。皆沉船,破釜甑,持三日糧。', en: 'Give a general +3/+2; deal 2 damage to your hero. Sink the boats, smash the pots — three days of rations.' },
  },
  {
    id: 'strat-yuanjiao-jingong',
    collectorNo: 9012,
    name: { zh: '遠交近攻', en: 'Befriend the Far, Attack the Near' },
    type: 'stratagem',
    doctrine: 'ritual',
    dynasty: 'warring-states',
    rarity: 'rare',
    archetype: 'strategist',
    cost: 3,
    keywords: [],
    spell: {
      ops: [
        { op: 'damage', amount: 2, target: 'chosenEnemyGeneral' },
        { op: 'draw', count: 1 },
      ],
    },
    text: { zh: '對一名敵方武將造成2點傷害,抽一張牌。廟算邦交,得寸則王之寸。', en: 'Deal 2 damage to an enemy general and draw a card. Every inch gained is the king’s inch.' },
  },
  {
    id: 'strat-meiren-ji',
    collectorNo: 9013,
    name: { zh: '美人計', en: 'Beauty Trap' },
    type: 'stratagem',
    doctrine: 'fame',
    dynasty: 'qun',
    rarity: 'legendary',
    archetype: 'strategist',
    cost: 6,
    keywords: [],
    spell: { ops: [{ op: 'destroy', target: 'chosenEnemyGeneral' }] },
    text: { zh: '消滅一名敵方武將。司徒妙算託紅裙,不用干戈不用兵。', en: 'Destroy an enemy general. No blades, no armies — one red gown.' },
  },
  {
    id: 'strat-shimian-maifu',
    collectorNo: 9014,
    name: { zh: '十面埋伏', en: 'Ambush on Ten Sides' },
    type: 'stratagem',
    doctrine: 'royal',
    dynasty: 'chu-han',
    rarity: 'epic',
    archetype: 'strategist',
    cost: 7,
    keywords: [],
    spell: { ops: [{ op: 'aoeDamage', amount: 3 }] },
    text: { zh: '對所有敵方武將造成3點傷害。垓下之圍,四面楚歌。', en: 'Deal 3 damage to all enemy generals. At Gaixia, Chu songs rose on every side.' },
  },
  {
    id: 'strat-shengdong-jixi',
    collectorNo: 9015,
    name: { zh: '聲東擊西', en: 'Feint East, Strike West' },
    type: 'stratagem',
    doctrine: 'neutral',
    dynasty: 'qun',
    rarity: 'common',
    archetype: 'strategist',
    cost: 2,
    keywords: [],
    spell: {
      ops: [
        { op: 'damage', amount: 2, target: 'chosenEnemyGeneral' },
        { op: 'damage', amount: 2, target: 'randomEnemyGeneral' },
      ],
    },
    text: { zh: '對一名敵方武將造成2點傷害,再對隨機敵方武將造成2點傷害。', en: 'Deal 2 damage to an enemy general, then 2 damage to a random enemy general.' },
  },
]
