import type { LocalizedText } from '../../engine/types'

// 白板卡的风味句 —— 97 张「一个字都没有」的卡。
//
// 【为什么正好是 97 张,以及为什么它们全是白板】
// 全池 2,451 张可收集卡里,卡面文案完全空白的只有 97 张,而且**全部是纯白板**
// (无关键词、无战吼、无光环)。带机制的卡至少有一行规则说明,白板卡什么都没有 ——
// 于是玩家看到的就是一个名字加两个数字。
// 这个游戏卖的是「这些人是真的」,而这 97 张恰恰是最不像真人的那一批。
//
// 【写作标准】
// 每一句都从那个人的生平里取,不编心理活动。引号里的话(「受將軍任,在此禦寇,
// 何敢委去」「苟利國家生死以」「春花秋月何時了」)都是原话。
// 拿不准的写他做过的那件事,不写他「如何想」——
// 和 lore-quotes.ts 的规矩一致,只是那边管名言、这边管卡面。
//
// 【为什么和 FLAVOR_OVERRIDES 分开放】
// 那份是「生成器漏掉的顶级传奇」,十几条,人工挑的;这份是**穷举**出来的一整批,
// 判据是机械的(text 为空)。两份混在一起,下次再想问「还有多少张没有文案」
// 就得先把它们分开。
export const VANILLA_FLAVOR: Record<string, LocalizedText> = {
  'yu-jin': { zh: '三十年古名將之風,一場大水衝盡。', en: 'Thirty years of an old general\'s bearing, undone by one flood.' },
  'mi-zhu': { zh: '徐州首富,把家產全押在一個還沒有地盤的人身上。', en: 'The richest man in Xu, betting his whole house on a lord with no land.' },
  'li-dian': { zh: '功多而不爭,讓功於同僚。卒年三十六。', en: 'He earned much and claimed none of it. He died at thirty-six.' },
  'zang-ba': { zh: '與孫權隔淮相望二十餘年,誰也沒過得去。', en: 'Twenty years across the Huai from Sun Quan, and neither ever crossed.' },
  'hua-xin': { zh: '見金而拾之,管寧於是割席。', en: 'He picked up the gold. Guan Ning cut the mat between them.' },
  'mao-jie': { zh: '他經手的任命,沒有一個是買來的。', en: 'Not one appointment that passed his hands was bought.' },
  'zhang-hong': { zh: '江東二張,一個守家,一個出使。', en: 'Two Zhangs held Jiangdong: one kept the house, one went to court.' },
  'guo-tu': { zh: '四世三公的家業,毀在幾句話上。', en: 'Four generations of high office, undone by a few words.' },
  'wu-lan': { zh: '前鋒出漢中,遇伏而沒。', en: 'Sent ahead into Hanzhong, and lost to an ambush.' },
  'wang-yi': { zh: '兒子在馬超手裡,她去說服了馬超的妻子。', en: 'Her son was Ma Chao\'s hostage. So she went and talked to Ma Chao\'s wife.' },
  'deng-zhi': { zh: '先主既死,是他一趟出使把吳蜀重新接上。', en: 'After the First Lord died, one embassy of his put Wu and Shu back together.' },
  'jiang-wan': { zh: '丞相死了,他不悲不喜,日夜操勞而面無慍色。', en: 'The Chancellor died. He showed neither grief nor relief, and worked day and night without a hard word.' },
  'liu-xie': { zh: '在位三十一年,沒有一天是自己的。', en: 'Thirty-one years on the throne, not one of them his own.' },
  'hu-zong': { zh: '凡他所奏,孫權都聽。', en: 'Whatever he proposed, Sun Quan heard out.' },
  'dong-xi': { zh: '受將軍任,在此禦寇,何敢委去!', en: 'I was given this post to hold off the enemy. How dare I leave it?' },
  'lu-fan': { zh: '袁術的舊部,鎮丹陽,撫山越,做到大司馬。', en: 'Once Yuan Shu\'s man; then Danyang, then the Shanyue, then Grand Marshal.' },
  'li-yan': { zh: '被廢為庶民之後他一直在等再被起用 —— 直到聽說丞相死了。', en: 'Stripped to commoner, he waited to be recalled — until word came that the Chancellor was dead.' },
  'liang-xing': { zh: '潼關敗走,後來還是降了。', en: 'Beaten at Tong Pass, and in the end he came over anyway.' },
  'han-fu': { zh: '他把冀州讓了出去,然後在別人家裡憂懼而死。', en: 'He handed Ji Province over, then died of fear in another man\'s house.' },
  'han-xian': { zh: '白波賊出身,護著天子走了一路。', en: 'A White Wave bandit who escorted the Son of Heaven the whole way east.' },
  'zhao-yan': { zh: '奉法持重,兩代皇帝都信他。', en: 'He kept to the law and kept his head; two emperors trusted him.' },
  'lu-fu': { zh: '往來吳國,靠的是一張嘴。', en: 'Back and forth to Wu, and his tongue was the whole of his equipment.' },
  'chen-shi': { zh: '出箕谷攻陳倉,敗;後來又被用了。', en: 'Out through Ji Valley against Chencang — beaten, then used again.' },
  'liang-xi': { zh: '鎮幷州二十餘年,北疆安靜。', en: 'Twenty years holding Bing Province, and the northern march stayed quiet.' },
  'bian-rang': { zh: '他寫詩諷了曹操一次,兗州因此反了。', en: 'He mocked Cao Cao in a poem, and Yan Province rose in revolt.' },
  'yu-quan': { zh: '據黑山,聚眾十餘萬。', en: 'He held the Black Mountains with a hundred thousand at his back.' },
  'xiang-lang': { zh: '坐馬謖之事被免,後來又用了回去。', en: 'Dismissed over the Ma Su affair, and brought back later all the same.' },
  'wei-guan': { zh: '鄧艾、鍾會滅蜀,事後兩人都死了,獨他還洛陽。', en: 'Deng Ai and Zhong Hui took Shu. Both then died, and only he rode back to Luoyang.' },
  'jinhuan-sanjie': { zh: '南蠻三洞元帥之一,陣前為趙雲所斬。', en: 'One of the three chieftains of the south, cut down in the field by Zhao Yun.' },
  'kebi-neng': { zh: '合鮮卑諸部為一,擁眾十餘萬。他一死,諸部又散了。', en: 'He made the Xianbei one, a hundred thousand strong. When he died, they came apart again.' },
  'fu-qian': { zh: '蔣舒詐降,他知道,仍然力戰不退。', en: 'Jiang Shu went over. He knew, and still would not give ground.' },
  'ji-ping': { zh: '鐵索加身,大罵不屈,最後撞階而死。', en: 'Bound in chains, cursing to the last, he broke his own head on the steps.' },
  'feng-xi': { zh: '夷陵一場火,他和張南都沒回來。', en: 'One fire at Yiling, and neither he nor Zhang Nan came back.' },
  'zhang-bu': { zh: '兩次立君,第二次立錯了。', en: 'He set two rulers on the throne. The second was the mistake.' },
  'yong-kai': { zh: '殺太守叛蜀,最後死在自己人手裡。', en: 'He killed the governor and broke with Shu; his own men killed him.' },
  'zhang-rang': { zh: '靈帝呼之為「阿父」。宮亂那夜,他投了河。', en: 'The emperor called him Father. On the night the palace fell, he went into the river.' },
  'jian-shuo': { zh: '西園八校尉之首,謀在靈帝崩的那一天,事洩。', en: 'First of the Eight Colonels. His plan was for the day the emperor died; it leaked.' },
  'liu-bian': { zh: '逃出北邙山那一年他十四歲,被鴆殺那年十六。', en: 'He fled over Beimang at fourteen; the poison came at sixteen.' },
  'deng-mao': { zh: '黃巾賊將。演義裡三英出場,第一個倒下的是他。', en: 'A Yellow Turban captain — the first man to fall when the three brothers took the field.' },
  'huan-fan': { zh: '他勸曹爽起兵。曹爽不聽,兩家一起夷三族。', en: 'He told Cao Shuang to raise troops. Cao Shuang refused, and both houses were exterminated.' },
  'e-huan': { zh: '被趙雲擒了,孟獲把他要了回去。', en: 'Taken alive by Zhao Yun, and Meng Huo asked for him back.' },
  'wang-fu': { zh: '麥城走到最後的那幾個人之一,被擒不降。', en: 'One of the last men out of Maicheng, taken alive and refusing to bend.' },
  'bian-hong': { zh: '他殺了孫翊,死在孫翊妻子的婚禮上。', en: 'He killed Sun Yi, and died at the wedding Sun Yi\'s widow arranged.' },
  'hist-han-jue': { zh: '趙氏一門盡誅,那個孩子是他保下來的。', en: 'The whole house of Zhao was put to death. The one child was his doing.' },
  'hist-zhibo': { zh: '引汾水灌晉陽三年。城沒破,他的頭骨成了酒器。', en: 'Three years turning the Fen against Jinyang. The city held; his skull became a drinking cup.' },
  'hist-you-yu': { zh: '本是戎人,回頭替秦國平了西戎。', en: 'Born among the Rong, and it was he who settled the Rong for Qin.' },
  'hist-qi-jinggong': { zh: '在位五十八年,養馬萬匹。孔子過齊,嘆了一聲。', en: 'Fifty-eight years on the throne and ten thousand horses in his stables. Confucius passed through Qi, and sighed.' },
  'hist-taizi-jian': { zh: '一句讒言,太子出奔;出奔之後也沒能活。', en: 'One slander sent the crown prince into exile. Exile did not save him.' },
  'hist-zijia-ji': { zh: '鄭國執政,最後與公室相爭。', en: 'He governed Zheng, and ended at odds with the ducal house.' },
  'hist-tian-dan': { zh: '七十餘城只剩兩座,他從即墨打了回去。', en: 'Seventy cities lost, two left. He came back out of Jimo and took them all.' },
  'hist-shendao': { zh: '法家講「勢」的那一支,從他起。', en: 'The Legalist school of positional power begins with him.' },
  'hist-yan-huiwang': { zh: '他換掉了樂毅,然後用一封信悔了一輩子。', en: 'He replaced Yue Yi — and spent the rest of his life regretting it in one letter.' },
  'hist-qi-jie': { zh: '他接了樂毅的位置,接到了火牛陣。', en: 'He took Yue Yi\'s command, and took the fire-oxen with it.' },
  'hist-gao-jianli': { zh: '眼睛被熏瞎之後,他把鉛灌進了筑裡。', en: 'After they blinded him, he poured lead into his lute.' },
  'hist-zou-yang': { zh: '一封獄中上書,把自己說了出來。', en: 'One letter from prison, and he talked his way out of it.' },
  'hist-chu-zhaowang': { zh: '郢都陷了,申包胥在秦廷哭了七天。', en: 'Ying fell. Shen Baoxu wept seven days in the Qin court.' },
  'hist-shao-hu': { zh: '公子糾敗了,他沒有像管仲那樣活下來。', en: 'Prince Jiu lost. He did not do what Guan Zhong did.' },
  'hist-chen-yu': { zh: '刎頸之交,最後在泜水兩邊。', en: 'Sworn to die for each other — and they ended on opposite banks of the Zhi.' },
  'hist-sima-ang': { zh: '項羽封的殷王,韓信破的殷王。', en: 'Made King of Yin by Xiang Yu, unmade by Han Xin.' },
  'hist-wu-chen': { zh: '略趙地而自立,死在自己的部將手裡。', en: 'He took Zhao and crowned himself; his own officer killed him.' },
  'hist-zhou-shi': { zh: '他替別人立了魏王,自己死在亂軍中。', en: 'He set another man up as King of Wei, and died in the rout.' },
  'hist-luan-bu': { zh: '詔書說敢收視者捕之。他去哭了。', en: 'The edict said: whoever mourns him will be seized. He went and mourned.' },
  'hist-xiao-duoli': { zh: '白登之圍那一年的匈奴單于。', en: 'The Xiongnu chanyu of the year they ringed Baideng.' },
  'hist-huan-chu': { zh: '陸賈來說降,他沒答應。', en: 'Lu Jia came to talk him over. He said no.' },
  'hist-zhufu-yan': { zh: '推恩令:不削藩而藩自削。他自己被夷了三族。', en: 'His edict shrank the fiefs without taking a thing. His own three kindreds were put to death.' },
  'hist-bu-shi': { zh: '牧羊出身,治民如治羊 —— 惡者輒去。', en: 'A shepherd by trade; he governed men as he governed sheep — cut out the bad ones early.' },
  'hist-huan-kuan': { zh: '鹽鐵會議上那場辯論,是他記下來的。', en: 'The great salt-and-iron debate survives because he wrote it down.' },
  'hist-liu-yao': { zh: '洛陽一敗被擒,前趙就沒了。', en: 'Taken at Luoyang, and Former Zhao went with him.' },
  'hist-xiao-gang': { zh: '父親餓死台城,他繼位,然後被侯景殺了。', en: 'His father starved in the palace. He took the throne, and Hou Jing killed him.' },
  'hist-zhangsun-wuji': { zh: '唐初第一功臣,死於一句「不可」。', en: 'First among Tang\'s founding ministers, undone by a single refusal.' },
  'hist-heichi-changzhi': { zh: '百濟降將,替唐打了突厥與吐蕃,死於構陷。', en: 'A Baekje general who fought the Turks and Tibet for Tang, and died on a false charge.' },
  'hist-feng-changqing': { zh: '退守潼關是對的。殺他的是一句讒言。', en: 'Falling back to Tong Pass was right. What killed him was a whisper.' },
  'hist-lai-ji': { zh: '反對立武后,流死崖州。', en: 'He opposed making Wu a empress, and died in exile at Yazhou.' },
  'hist-li-yu': { zh: '春花秋月何時了。', en: 'Spring flowers, autumn moon — when will they ever end?' },
  'hist-meng-chang': { zh: '十四萬人齊解甲,更無一個是男兒。', en: 'A hundred and forty thousand laid down their arms, and not one of them a man.' },
  'hist-ouyang-xiu': { zh: '醉翁之意不在酒。他點了蘇軾。', en: 'The Old Drunkard\'s mind was never on the wine. He was the one who picked Su Shi.' },
  'hist-jia-sidao': { zh: '專權二十年,鬥了二十年蟋蟀。', en: 'Twenty years in power, twenty years of cricket fights.' },
  'hist-tong-guan': { zh: '掌兵二十年,北伐屢敗,金兵因此南下。', en: 'Twenty years with the armies; every northern campaign failed, and the Jin came south.' },
  'hist-niu-gao': { zh: '岳飛死後,他憤而卒。', en: 'After Yue Fei was killed, he did not last long.' },
  'hist-yang-zheng': { zh: '鎮西夏邊境。', en: 'He held the marches against Xia.' },
  'hist-ye-shi': { zh: '永嘉學派講功利,他和朱熹講的不是一件事。', en: 'The Yongjia school spoke of use and benefit — not at all what Zhu Xi was speaking of.' },
  'hist-yang-yansi': { zh: '楊業七子之一,隨父兄抗遼,陣亡。', en: 'One of Yang Ye\'s seven sons; he went north with his father and did not come back.' },
  'hist-zhao-boju': { zh: '宗室畫青綠山水,《江山秋色圖》傳世。', en: 'A prince who painted the blue-green mountains; his Autumn Colours still survive.' },
  'hist-guo-shoujing': { zh: '一年三百六十五點二四二五日 —— 比西方早了三百年。', en: '365.2425 days to the year — three centuries before the West got there.' },
  'hist-sangha': { zh: '世祖的權臣,最後因貪贓被殺。', en: 'The Khan\'s strongman, executed in the end for what he took.' },
  'hist-hai-rui': { zh: '上疏之前先買好了棺材。', en: 'He bought his own coffin before he sent the memorial.' },
  'hist-qi-tai': { zh: '削藩是他倡的,燕王進了南京之後夷了他三族。', en: 'He argued for cutting the princes down. When the Prince of Yan reached Nanjing, three kindreds paid.' },
  'hist-xia-yuanji': { zh: '五朝戶部尚書。明初的帳都在他手上。', en: 'Minister of Revenue under five reigns — the early Ming\'s books were all in his hands.' },
  'hist-chongzhen': { zh: '自縊煤山,以髮覆面。', en: 'He hanged himself on Coal Hill, his hair pulled down over his face.' },
  'hist-lin-zexu': { zh: '苟利國家生死以,豈因禍福避趨之。', en: 'If it serves the country, I will meet life or death — and not step aside for either.' },
  'hist-tan-sitong': { zh: '我自橫刀向天笑,去留肝膽兩崑崙。', en: 'I face the blade and laugh at heaven — those who go and those who stay are both mountains.' },
  'hist-yang-rui': { zh: '戊戌六君子之一,慷慨就義於菜市口。', en: 'One of the Six Gentlemen of 1898, executed at the vegetable market.' },
  'hist-tongzhi': { zh: '兩宮垂簾,他在位十三年,活了十九歲。', en: 'Two dowagers behind the screen; thirteen years on the throne, and nineteen years alive.' },
  'hist-yikuang': { zh: '皇族內閣首席。當時的人叫他「慶記公司」。', en: 'Head of the imperial cabinet. People of the day called his office a trading firm.' },
  'hist-jiang-zhongyuan': { zh: '塾師出身,帶兵打太平軍,死在廬州。', en: 'A village schoolmaster who raised troops against the Taiping, and died at Luzhou.' },
  'hist-wu-weiye': { zh: '《圓圓曲》一首,寫盡了那一年。', en: 'One ballad of Chen Yuanyuan says everything about that year.' },
  'hist-gao-shiqi': { zh: '以詩書畫得幸於康熙。', en: 'Poetry, calligraphy and painting were how he came to the Kangxi emperor\'s notice.' },
}
